### ISSUE TITLE
Surgery Incorrectly Defaulting From First Aid

### ISSUE THREAD

**Issue by CaptainJoy** [richardwilkes/gcs#122]
The Surgery skill has First Aid -12 as a default, as it should be.  But it doesn't always work that way.  If you add First Aid and Surgery to a blank character sheet, they'll each have 1 point assigned to them.  The First Aid skill will be IQ+0, as it should be.  The Surgery skill will be IQ-2, with or without having 1 point in it, which is way to high.

With 1 point in FIrst Aid, Surgery is at IQ-2.  With 2 or 3 points in FIrst Aid, Surgery is at IQ-3.  With 4 to 7 points in First Aid, Surgery is "-".  With 8 points in First Aid, Surgery is at IQ-9 — which for the first time is a RSL 12 less than FIrst Aid.
(It is a VH skill, but it has no IQ default.)
My guess it's some weird effect due to the edge case of having a "-12" default.  it's just _too much_!  :)

**Comment by crnormand** [comment]
A default for a skill is only used if you do not have any points in the skill itself.   So if the character were trying to perform a surgical procedure, and all they knew was First Aid, then they would try the roll at First Aid - 12.

But once the character puts 1 single character point into the skill, then the skill is based on the underlying attribute, in this case IQ.   Surgery (B223) is an IQ/VH skill (based on IQ, Very Hard).  The table on B170 shows that 1 point spent on a "Very Hard" skill, give you a starting value of Attribute - 3, so in this case, IQ-3.

**Comment by CaptainJoy** [comment]
Agreed on all accounts. This is what I’m seeing:



If you’re not able to reproduce the above behavior, the problem may be on my end.

**Comment by crnormand** [comment]
It seems to be calculating the default correctly (on my machine).   When I changed the character points from 1 to 0 on the Surgery Skill, it drops to First Aid -12 (well, actually, on my test character, it dropped to Vet-5, since it was a druid), but when I deleted the Vet skill, it dropped to 0, because this character's FirstAid is only a 12, and 12-12 = 0 ;-).

When I raised FirstAid to 15, Surgery became a 3.

**Comment by richardwilkes** [comment]
@CaptainJoy please post a minimal character sheet that illustrates the problem for you.

**Comment by CaptainJoy** [comment]
Here is the villain!

This is decidedly an edge case.  I’d I believe you’re working on a major overhaul/HTML-version anyway?  If so, feel free to drop this issue.

**Comment by richardwilkes** [comment]
While I am indeed working on a major new revision, that effort stalled more than a year ago due to a lack of time, a lack of an active game to use it with (my current group is playing Pathfinder, although I'd prefer GURPS), and a general lack of interest on my part when it comes to JavaScript, which is what the front-end needs for the particular route I chose (using the language Go as a backend [implemented and working great] and web server and a web browser for the front end display). I hope to return to it someday, but will likely need someone that enjoys and is knowledgable about JavaScript to help.

At any rate, if there is an issue here, we should get to the bottom of it. @crnormand's analysis seems to indicate there isn't an issue... if you are still seeing a problem, please post a sheet so that we can reproduce it (I didn't see any attachment).

**Comment by CaptainJoy** [comment]
Since my attachment didn’t make it last time, try downloading it from my PCs webpage <http://captainjoy.chunkyboy.com/PCs/PCs.php>; it’s at the bottom of the page.  It’s the character named “Test FA Surgery.gcs <http://captainjoy.chunkyboy.com/PCs/Test%20FA%20Surgery.gcs>”.

All it is is a character with two skills: First Aid and Surgery

I’m getting the following odd behavior when Surgery has 0 points in it.

Points in First Aid
0
1
2
3
4
8
12
16
First Aid Skill Level
6
10
11
11
12
13
14
15
Surgery Skill Level - GCS
-
8
7
7
-
1
2
3
Surgery Skill Level - GURPS
-
-
-
-
-
1
2
3

Note the disagreement between GCS and GURPS RAW when 1, 2, or 3 points are put into First AId.

When Surgery has 1 point in it, it give 7 as the skill level (which is correct), but gives 8 as the skill level when there is 1, 2, or 3 points in First Aids.

**Comment by richardwilkes** [comment]
I had a few spare minutes this evening and took a look... and this is being caused by code in `getBestDefaultWithPoints()` (Skill.java:849) which is setting the points to a positive value because the adjusted default level went below 0, which is not correct. Normally, a negative value here is used to trigger special logic elsewhere, but that doesn't happen because the negative value is being turned into a positive one in this case. I'll have to give this some thought on how to correct it and not break the regular handling.

**Comment by CaptainJoy** [comment]
I suspect it rarely comes up; I mean, this program has been in the wild for years and we’re just now noticing this.

Thank you so much for this wonderful program!

**Comment by richardwilkes** [comment]
Turns out the actual fix was easy. It will show up in the next release (whenever that happens), or you can grab the source and build it yourself if you need it right now.
