### ISSUE TITLE
Gunner (Cannon) not being recognized

### ISSUE THREAD

**Issue by ssveter1** [richardwilkes/gcs#126]
Gunner (Cannon) not being recognized. I Even created new skill for the ship's guns...and no, was not recognized and did not calculate SL.

**Comment by richardwilkes** [comment]
Please attach an example sheet that illustrates the problem

**Comment by ssveter1** [comment]
Please see attached

**Comment by richardwilkes** [comment]
Nothing was attached that I can see. GitHub will throw away attachments that don't have an extension it likes -- one of GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP. You will probably need to zip the file up to attach it.

**Comment by richardwilkes** [comment]
Still nothing. It looks like you're trying to do this via email -- maybe it only works if you log into the site and do it using their interface?

**Comment by ssveter1** [comment]
Dang it, ok

**Comment by ssveter1** [comment]
![GCS Screenshot](https://user-images.githubusercontent.com/10831302/62087236-05154d80-b22f-11e9-8dee-0c615f423397.jpg)

**Comment by richardwilkes** [comment]
The image came through that time... but could I get you to attach the .gcs file so that I can see exactly what you've done?

**Comment by ssveter1** [comment]
[Low Tech Equipment.zip](https://github.com/richardwilkes/gcs/files/3444472/Low.Tech.Equipment.zip)
[2019_07_12_Ronald_Calwell.zip](https://github.com/richardwilkes/gcs/files/3444476/2019_07_12_Ronald_Calwell.zip)

**Comment by richardwilkes** [comment]
So when I open the Ronald Calwell sheet up and look at it, there are two entries for the cannon in the weapons table, one for Direct Fire and one for Indirect. Indirect has a skill level, while the Direct Fire does not. The reason is, the Direct Fire settings have a minimum ST listed well above your character's ST, resulting in penalties that completely eliminate your ability to use the weapon. Remove that ST requirement and the skill level will be populated (albeit not from the skill "Gunner (Cannon)", as that's not listed for that entry).

**Comment by ssveter1** [comment]
I see
