### ISSUE TITLE
GCS 4.12 Immediately quits on start

### ISSUE THREAD

**Issue by mjeffw** [richardwilkes/gcs#137]
Just downloaded the new version to my Mac laptop running Mojave. Launching the application; it opens briefly and then quits.

I see the following message in the Console:

Failed to copy signing info for 27767, responsible for file:///Applications/GURPS%20Character%20Sheet.app/Contents/MacOS/GURPS%20Character%20Sheet: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"

**Comment by richardwilkes** [comment]
I do not sign GCS, as that requires signing up for and paying yearly for a developer account, which I am not willing to do, given that I create the software for free in my own time and already shoulder considerable costs to do so.

To install & run GCS, you'll need to set the Security & Privacy preferences to "App Store and identified developers" (rather than just "App Store") and then for the very first time you try to open it, you'll need to instead right-click on it and select "Open" from the context menu... which will then present a dialog with an "Open" button. Click on that. After doing this once, macOS will remember and not bother you again about it. Unfortunately, they've made it particularly annoying (and difficult, for someone that doesn't know what they are expected to do).
