### ISSUE TITLE
Advantage Features - Bug in "Skill Whose Name Contains" Per level

### ISSUE THREAD

**Issue by RevenantBob** [richardwilkes/gcs#142]
This was performed on Windows 10 with version 4.13.3 installed from MSI.

**Reproduction**

1. Create new character
2. Create a skill named "Test Skill" with 1 point in it
3. Create an advantage named "Test Advantage"
4. Set "Has Levels" and add levels
5. Create a Feature for the advantage "Gives +1 per level" with "skills whose name contains" and "Test". Specialization in anything and blank. Category is anything and blank.

**Observed Result**
Skill level is not modified and 9.

**Expected Result**

Skill level should increase with the levels of "Test Advantage".

**Comment by richardwilkes** [comment]
Thanks for the concise steps to reproduce. Looks like at least the comparison for string containment has suddenly broken. :-(

**Comment by RevenantBob** [comment]
No problem =) I work as a software engineer. I'm used to writing all the steps to reproduce.

**Comment by richardwilkes** [comment]
Turns out the issue was in the new code that @crnormand had added earlier this year to support adjustments based on categories. Anyway, easy fix. If you have the time & ability to build GCS yourself and verify this works, I'd appreciate it. I don't have anything else pending right now, but this is worth creating another bug fix release for, I think.

**Comment by crnormand** [comment]
I hope it was something I did late at night.

I would be embarrassed if I made a simple mistake in the bright light of day.  :-)
