### ISSUE TITLE
Ability to enter floating point value for advantage cost

### ISSUE THREAD

**Issue by dgtexan** [richardwilkes/gcs#151]
Dungeon Fantasy 9: Summoners
Hordes of Minions (infobox on p. 14):

> Optionally, the rules for Allies (pp. B36-B38) can be expanded to cover extremely low-powered servants. Instead of a base cost of 1 point for any Ally built on 25% or less of the PC's point value, use the following fractional base costs: 0.2 points for an Ally built on up to 5%, 0.4 for up to 10%, 0.6 for up to 15%, and 0.9 for up to 20%. In all cases, apply the multipliers for frequency of appearance, ally groups, and all modifiers before rounding the cost up to the next-higher whole number of points

I know it's only one ability (that I've found) that requires this, but it would still be nice to be able to put float numbers in costs. I know you have the Animate Dead ability of the Gray Necromancer from PY3:50 already filled out as a flat cost, but I prefer to use the calculations where I can instead of flat costs in case I want to apply other modifiers for whatever other homebrew reasons. 

Thank you for an awesome app so far!!

**Comment by richardwilkes** [comment]
This would be a fairly sweeping change, as points are tracked as an integer throughout the code and changing it to a floating point value would necessitate updating everything that dealt with points. Due to this, the fact that it can be pre-computed if needed, and that it has extremely limited utility (i.e. only one case where it is needed), I'm unlikely to make such a change any time soon. I'll keep this around as a reminder, though, in case someone else wants to take this on and make the necessary changes.

**Comment by richardwilkes** [comment]
You could also model this by adding additional modifiers for the sub-point variants. i.e. select the modifier that gives 1 point for the base cost, but then apply a modifier for being less than one point: x0.2 for the 5% case, etc.

**Comment by richardwilkes** [comment]
When GCS v5 was being written, the underlying system permitted this from the start.
