### ISSUE TITLE
Application freezes every time I open a character sheet.

### ISSUE THREAD

**Issue by Taustin442** [richardwilkes/gcs#157]
I was using an old version for quite some time and last night updated to the latest (the date on the .exe of the old one is 01/08/19 but I don't know what version).

All last night I had no problems using the application. I made a character saved it, turned off my computer. 

Today if I open the character I made last night, open a character that comes packaged with the install, or even create a new character sheet, all of the UI freezes. Windows doesn't mark the program as frozen but nothing responds, and the only way to close it is with the task manager.

I can open skill lists, character templates, and pretty much anything else that doesn't open a character sheet, but character sheets won't open.

I've tried reinstalling it several times, I've tried installing it in a different location, I've tried running in admin mode and compatibility mode. 

I'm at a total loss to what is wrong. I can tell preferences are being stored somewhere because all installs still have my preferences from the old version. I found a gcs.pref in AppData local and tried removing that. It cleared my preferences but the issue still exists. Are there any other things that don't get removed with an uninstall?

I'm on windows 10 if that is helpful.

Edit: Removed that the old copy doesn't work. It does it just can't load the new character which is expected.

**Comment by richardwilkes** [comment]
This happens when you just create a new character sheet? ... and did not happen when using it the previous day? The most likely culprit is an OS extension that is causing some sort of issue. The first thing I'd try is to disable any such extensions / modifications, reboot, and see if it still happens. You might also want to try creating a temporary new user and trying GCS inside that account to see if it is something specific to your user account that got mangled.

Other than the above, and maybe ensuring your system is up to date with all of Microsoft's latest updates, I'm at a loss as to what would be causing this. You're the only one reporting it so far, and I'm not having any such issues on any of the Windows machines I've tried it on. :-(

**Comment by Taustin442** [comment]
Good call on trying a different user. It works in the tempory user account I added but not my main one. Is there a common way to fix whatever is wrong on my user account? 

Thank you for your help. as well as your fast response time.

**Comment by richardwilkes** [comment]
Unfortunately, I don’t have any real suggestions beyond disabling any customizations you may have enabled for your user account. Windows is not something I use on a regular basis. Wish I could be more helpful than that.
