### ISSUE TITLE
Show User Descriptions in saved html files and GURPS Calculator after export

### ISSUE THREAD

**Issue by Euthoniel** [richardwilkes/gcs#164]
Currently they disappear.

**Comment by richardwilkes** [comment]
This is intentional, as this field was created specifically to hold data that Steve Jackson Games might object to GCS including in any distributed files. This is permitted as long as you just use it yourself, but letting that data flow through to libraries or things like gcalc would cause problems and eventually get GCS shut down. Therefore, I will not be expanding support for this.
