### ISSUE TITLE
Add weapon button missing

### ISSUE THREAD

**Issue by faenocasul** [richardwilkes/gcs#17]
Hello Richard Wilkes!

I´ve been using GCS for like ten years now. Thank you ver much btw! :)

The latest version 4.10 is missing the "add ranged weapon" and "add melee weapon" buttons:

![gurps workspace](https://user-images.githubusercontent.com/33199570/32144635-2f387d4a-bcbc-11e7-905f-db79d5d8589f.png)

Am I missing something?

Best regards
Jens Reinemann

**Comment by richardwilkes** [comment]
Hi, Jens.

Nothing in that area has changed. There has been a long-standing issue on some Windows machines where the add button is invisible for some reason — you’ll note in your screen shot that there is a space for it right above the ‘-‘. You could try clicking where it should be to see if the button itself still responds. Anyway, I’ve never been able to replicate this particular problem on any platform. Until I do, I’m unlikely to be able to determine what the problem is and fix it. I’ve already examined the code in question many times looking, but it all seems to be good — and certainly no different than the code for any of the other buttons with pictures on them.

One thing that has helped some people is to create a brand new account on their machine and run the software there, as if some setting in Windows is the culprit. Once again, no one has been able to narrow down what that might be, though. Sorry I can’t be more helpful.

- Rich

**Comment by faenocasul** [comment]
Hi Rich!

You´re right! The button is there, but the "+" symbol is invisible!

Thank you a lot!
Jens

(Btw, it´s a pretty default Windows 10 (x64, EN with German Keyboard, Java 1.8.0_144))

**Comment by engleback** [comment]
Hi Richard, I did some work back on GCS and I do think I addressed this issue with a possible solution, but if I recall this would have been on JIRA, it's been a while sinced I have worked on the project and going direct via GitHub is new to me, would you be able to drag out the change file I created and I can see if I can have another shot at this? Ian

**Comment by richardwilkes** [comment]
I don't see it anywhere, @engleback -- I do remember someone attempting to find a fix, but the effort I'm thinking of didn't pan out. At this point, I'm thinking it might actually be the image itself -- perhaps it was created oddly. I'm going to recreate it and see if that helps anything. If you can reproduce the issue, then I'd be interested in getting your feedback on whether the updated image fixes the problem once I check it in.

**Comment by richardwilkes** [comment]
I've now updated the image in the toolkit source tree. If you rebuild both toolkit and gcs, you should get the new version.

**Comment by richardwilkes** [comment]
Spent some more time on this tonight... with zero luck. There is something weird going on with only Windows, where the icon in the button just will not display if it is enabled. Disable it and it shows up just fine. What is even more bizarre is that the exact same code to create a small "add" button is used elsewhere and doesn't exhibit this behavior. Reordering things doesn't help. Using different images doesn't help. Anyway, I'm officially giving up on this. Windows is full of bizarre stuff that has made developing GCS extremely painful, and I'm chocking this up to yet another of those cases.
