### ISSUE TITLE
GCS Mac Version 4.15 not working - "damaged" file

### ISSUE THREAD

**Issue by TheFabulousIronChef** [richardwilkes/gcs#176]
Got an error message:

<img width="419" alt="Screen Shot 2020-05-11 at 10 36 10 AM" src="https://user-images.githubusercontent.com/46587602/81584567-e547b400-9380-11ea-9138-1277b051a2a8.png">

**Comment by richardwilkes** [comment]
Unfortunately, that's due to the latest version of macOS being overly restrictive. I do not have the ability to sign the code at it now wants. That requires an Apple Developer account, which I'm unwilling to pay for given it is a yearly fee and this is software I already donate a *huge* amount of my time and effort to.

To get around it, you need to open a terminal and issue the command:

xattr -d com.apple.quarantine /Applications/GCS.app

(assuming you put GCS into the Applications directory)

**Comment by TheFabulousIronChef** [comment]
Oh, got it. Thank you very much!

**Comment by TheFabulousIronChef** [comment]
Also: Thanks for working on this program. Much appreciated.

**Comment by richardwilkes** [comment]
For the time being, I've placed a notice on the GCS web site about this issue and how to get around it.

**Comment by richardwilkes** [comment]
I've received enough donations to cover the first year of an Apple Developer Account, so I went ahead obtained the necessary account and certs to sign the macOS distribution. I'm in the process of determining how to make this all work, but this commit d34430dfaeaeb5f0c80f69af40da10192c0da82a add support for at least making the distribution something you can now open again on macOS without needing to resort to the command line. Unfortunately, it still isn't enough to be completely invisible -- the OS still pops up a warning, but if you then right-click and tell it to open, it will. Next step is to figure out a way to submit the package for notarization by Apple, which will then eliminate this problem... but it needs to be something I can do in a mostly automated way, so that could take some time to figure out as well.

**Comment by richardwilkes** [comment]
This should have been fixed as part of the 4.16 release.
