### ISSUE TITLE
Deleted Data

### ISSUE THREAD

**Issue by CaraiseLink** [richardwilkes/gcs#179]
While I appreciate that _now_ we have a separate user library, I wish you would've implemented it in a way that didn't delete everything I'd added to my library in the previous version. The installer didn't display a warning about deleting anything, and I didn't think to back everything up first, so I've lost dozens of hours' worth of effort. I even tried downloading and running a file recovery program immediately afterwards, no luck.

I'm more than a little bit upset, and I'm not entirely sure I want to trust future updates unless my GM requires me to. Nothing this update could've done would've been worth it.

**Comment by richardwilkes** [comment]
It is unfortunate that the installer overwrote your data. I just use what the platform provides. Since I have little to no control over the installer itself, I took the time and effort in this recent release to move the data completely outside of the software package. That doesn’t help you now, obviously. Neither does complaining to me... I created this software and share it to the world for free — something that I’ve invested many thousands of man-hours developing. Feel free to never use my software again.
