### ISSUE TITLE
Equipment Modifiers Incorrectly use -80% Maximum Reductiom Rule, and Multipliers don't Multiply.

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#187]
Equipment modifiers are apparently using the 80% maximum cost reduction rule. This is incorrect. For example, when I apply an equipment modifier of SM-5 (from GURPS 4e Low Tech Companion 2), the cost should be multiplied by 0.04. The *weight* is correctly modified though.
![image](https://user-images.githubusercontent.com/1914417/82029520-7b117500-96da-11ea-8cdb-ae69b40b1894.png)

**Comment by Legendsmith** [comment]
Additionally, Multipliers do not multiply correctly, they add.
![image](https://user-images.githubusercontent.com/1914417/82031336-173c7b80-96dd-11ea-8baf-d7c9a6d78f3f.png)

**Comment by Legendsmith** [comment]
I think the solution to this is use more informative labels so it's less confusing. like for example, the 'base cost' should be labelled "additive base cost/CF" because that's what it is.
The other thing is that things like 'original cost' don't support x2 and x0.5 type modifiers. This 2nd point more more convenience as the percentages can be calculated anyway.

**Comment by richardwilkes** [comment]
So the maximum reduction is only applied to the one step that includes CF adjustments. This is due to the rule on LT14: "If total CF is below -0.8, treat it as -0.8; thus, final cost cannot be below 20% of list cost." My assumption (and semi-verified by a statement by Kromm that he would redo all of the old books to present equipment cost multipliers as CF if he had the chance) is that the multipliers I allow at this stage should be converted into CF and applied as CF and therefore the same lower limit should be applied. If you want to adjust things below that threshold, you must do them in a different step where the only limit is a floor of 0.

**Comment by richardwilkes** [comment]
Linking to a PR in the gcs_library that also discusses this: https://github.com/richardwilkes/gcs_library/pull/114

**Comment by Legendsmith** [comment]
Ok, so Original cost doesn't use the lower floor of CF then? Training Weapons (LTC2:13) have cost multipliers of 0.05 for example. That's good.
- Pyramid 37: Tech and Toys 2 - Thinking Machines
- SM Modifiers (Low Tech Companion 2, also High Tech and Ultra Tech).

I think there's a little bit of confusion, since the CF modifiers are called "Base cost" in GCS but when the books refer to "base cost" they mean something more like original cost. Clearing this up and renaming "original cost" to "base cost" and what's currently "Base cost" to "Cost modifier" could prevent confusion

**Comment by richardwilkes** [comment]
There are 4 stages, though... the names picked were an attempt (clearly failed) to convey some info on what was happening. What the rulebooks call it isn't terribly useful, as they contradict each other in many cases, sometimes in the same book. Well, "contradict" might be too strong of a word -- conflate, perhaps? Point is, they aren't consistent in terminology nor in how modifiers are applied (ordering, multiplication vs addition, etc). What you see in the UI is an attempt to allow all that to co-exist in a way that I can actually interpret it from a computer's point of view, rather than requiring human intuition as to what something means and how it should be applied.

Anyway, I am open to other naming or even to some sort of expanded explanation somewhere that can be referred to. At the moment, the current choices seem to be adequate to represent how I think about it from the code point of view. Ideally, what's presented would make sense to users, though. The books essentially refer to at least 3 different "base costs", for example.

**Comment by richardwilkes** [comment]
Maybe I should give up on trying to find meaningful names and just call them "step 1", "step 2", etc. (or maybe "stage 1") and then rely on something somewhere else (tooltip?) that tried to explain in more detail what was actually meant?

**Comment by Legendsmith** [comment]
Yeah, the inconsistency certainly isn't helpful. Now, on modifiers. SM modifiers need to be multiplied with others such as the training weapons; The cost of a Heavy blunt training weapon for a SM-4 pixie is x0.09 (SM modifier). and x0.2 (Heavy blunt modifier). This could potentially be represented currently, because it's just 2 modifiers. The Heavy Blunt could be applied to 'original' cost and the SM modifier to final, I think? I'm not actually sure what Final cost modifiers do precisely. 

I think another part of the solution here is to develop a convention for what modifiers are where. For example, SM modifiers could always be the "Final" modifier, and CF modifiers always the "to base cost" modifier, for example.

**Comment by richardwilkes** [comment]
Yes, there are definitely assumptions about what goes into which stage.
