### ISSUE TITLE
Features on Modifiers do not Stack

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#190]
I'm not sure if this is intentional, maybe it is, but maybe not.
Replication:
1. Create an item.
2. Create a modifier that gives +1 to DR, or any attribute.
3. Apply it to the item.
4. Increment the quantity of the item.
5. Note that the DR or attribute doesn't increase.

**Comment by Legendsmith** [comment]
If this is intended, then I suggest that selecting "per level" for the feature modifier take into account quantity and treat it like the level.

**Comment by richardwilkes** [comment]
Per-level is meaningless on a feature that isn't attached to a leveled advantage. There is no such thing as leveled equipment (at least not in GCS -- I wouldn't put it past SJG to have snuck such a thing in somewhere, though). Features are generic in that they can be attached to either advantages or equipment, which is why you're seeing such options, despite them doing nothing useful. With enough effort, I could alter the display for equipment to omit those fields, but that's more work than I'm likely to give to this particular problem any time soon.

**Comment by richardwilkes** [comment]
Hmm... I guess you're asking for quantities above 1 to be treated as multiple copies of any features that item provides. That would be possible, though expensive to do, since the way this works in putting individual copies of a given feature in a map for lookup elsewhere to apply affects... which would rapidly get out of hand when someone put even a modest number in the quantity field of an item that provides features. If you really want multiple, right now you have to separate them onto separate entries to get their effects to apply from each.

**Comment by richardwilkes** [comment]
Due to the potential to cause GCS to appear to lockup from putting in large-ish numbers into the quantity field should I implement this, I'm not going to do so. If you really want the effects of multiple items to apply to your character, you'll need to separate them into distinct entries, like mentioned above.
