### ISSUE TITLE
Support for Stacked Equipment Uses 

### ISSUE THREAD

**Issue by LawfulDickish** [richardwilkes/gcs#198]
At the moment, the max uses field for equipment only takes numbers, and remains static no matter how many copies of that equipment is stacked up. An option to have max uses be the given number * pieces of equipment in a stack would allow for the ability to take quick stock of the amount of uses left on a stack of multi-use equipment, such as containers of food that last for multiple meals.

**Comment by richardwilkes** [comment]
I've always viewed the uses field as the number of remaining uses for a single instance of the piece of equipment and should I do something that drops it to zero, I then decrement the quantity of the item and reset its uses field back to max. You're right that this doesn't give an at-a-glance summary for you, but I'm unconvinced that's actually useful enough to warrant potentially confusing UI to enable such a feature.

This is similar to the issue around having a quantity greater than 1 on a container -- I almost never do this, since it means any edits to the container's content affect all of them, not just one of them.

Anyway, I'm going to close this since I have no desire to implement it. Should you come up with a brilliant solution, I'm willing to hear the suggestion.
