### ISSUE TITLE
FoundryVTT Integration

### ISSUE THREAD

**Issue by justinthejaguar** [richardwilkes/gcs#207]
Is it possible to integrate GCS with the FoundryVTT Game Systems? https://github.com/foundry-vtt-community

**Comment by richardwilkes** [comment]
I'm unlikely to do so, as I don't have that product. Depending on what you're trying to accomplish, GCS's export templates could allow you to do some integration.

**Comment by jbhuddleston** [comment]
I have built a minimal implementation of GURPS4E for Foundry VTT (as discussed on Discord #chat-vtts-and-maps) and, once it is working as well as I think it needs to, wish to discuss with you whether or not it is worthwhile to pursue a full character sheet based on an export from GCS (like the Fantasy Grounds output templates); although I don't know if it was you or someone heavily involved in that VTT like Ronnke who built them. I learned enough about how they work to build one to match my data requirements (or build them to match your possible outputs :-) Cheers.

**Comment by richardwilkes** [comment]
Happy to collaborate where needed. I suspect everything you will need is already there. Once the basics are in place, we could consider adding deeper integration, such as an ability to transfer them directly to the VTT or possibly receive updates back, etc.

**Comment by jbhuddleston** [comment]
Thanks, although this is certainly some distance away. I am taking a day to learn more javascript as copying half-understood examples of existing code will only get one so far. I have a friend who is building a React app (because he wants to learn React) to link to a GCS file and render an html character sheet. When the GCS file changes the html file changes. At least that is what I think he is up to :-) He does this for a living, me for fun.

**Comment by richardwilkes** [comment]
Hmm.. you may want to contact Wiggles on the GURPS Discord. I showed him my (now ancient) attempt at re-writing GCS in Go with a web-based interface (and support for automatic updates when libraries change... sigh... I keep telling myself I should finish that work up, but it is now quite behind GCS's current state) and he's been experimenting with (I think) React and rendering GCS content since.

**Comment by jbhuddleston** [comment]
Thanks much. I will pass that on.

**Comment by richardwilkes** [comment]
@jbhuddleston I know both you and Wiggles have made considerable progress on your GURPS integrations for Foundry. Perhaps you can add links here so that those browsing through might be able to find your work?

**Comment by jbhuddleston** [comment]
If you mean by here, in this issue, then here is the url to my project. https://gitlab.com/jbhuddleston/gurps4e

My published system for GURPS is available through the regular system installation process in Foundry.

Wiggles is working on his outside of Foundry as he has not yet applied to be added as an official Foundry system. As you mention above, he is taking the approach of integrating much more closely to GCS than I am.

His repo is at: https://github.com/WIGGLES-dev/GURPSFoundrySystem

Cheers,
James

**Comment by richardwilkes** [comment]
Thanks, @jbhuddleston

**Comment by crnormand** [comment]
You can also check out:  https://github.com/crnormand/gurps/tree/release

This is a Foundry VTT game system based on the GCS character sheet.     You can read more about it [here](https://docs.google.com/document/d/1NMBPt9KhA9aGG1_kZxyk8ncuOKhz9Z6o7vPS8JcjdWc)

**Comment by richardwilkes** [comment]
I'm going to go ahead and close this, as Chris' Foundry project imports from GCS quite nicely and I see no need for GCS itself to do anything more here. Should Chris need other features from GCS, I'm sure he will bring them up with me.

**Comment by justinthejaguar** [comment]
That is perfect. You should check it out if you ever get a chance. He is doing great work.

Thank you,
Justin Payton
