### ISSUE TITLE
Add the 'user notes' field to everything.

### ISSUE THREAD

**Issue by peruses** [richardwilkes/gcs#214]
Not an important change just having somewhere to put build notes and random verbose comments on equipment advantages and limitations without cluttering up the character sheet would be handy.

**Comment by jbhuddleston** [comment]
I put together a few of the comments on Discord and some made by Rich and believe this is more important for long-term benefit than stated above by peruses. To summarise: we all want the user libraries to be more easily maintained; we know that some features that are contained in the RAW are, as yet, unsupported in GCS and therefore are not present in GCS; and once a new capability is introduced in GCS, someone has to pore through the RAW to add the bits of rules that were missed.
I suggest that a user notes field for every element would allow a once-over of the rules to add the bits that are not currently implemented and store them with the object. This may not be as simple or even as beneficial as I believe but I think it is worth implementing sooner rather than later. Cheers.

**Comment by richardwilkes** [comment]
The current user notes support was added by a contributor that wanted it for something very specific -- hence the additions where they ended up and the controls to allow them to be shown directly in the lists, in a tooltip, or hidden altogether. He also, at my request, made it so that the user notes aren't actually persisted in the libraries -- only in the character sheet. The reason for this is to avoid having SJG coming in and telling me to shutdown the software because too much info has been put into the data files (this, by the way, was mostly what the original contributor wanted those fields for -- to essentially copy & paste significant sections of the rulebook into them for reference at his game table).

**Comment by jbhuddleston** [comment]
I may not have thought this all the way through but would the main complaint by SJG be that you could print out or view most of the rulebook during play?

If so, could you arrange it so that these notes were only available in the library and were not supported in user artifacts at all. Printing would similarly be curtailed. 
That would allow us to store future work in the library without it becoming illegally available to users.

**Comment by richardwilkes** [comment]
The issue from SJG's point of view is that they want to ensure there is a reason to buy their books. I can't blame them for that one bit. Where that line is, of course, is very subjective. It's their intellectual property, though, so their call.

If I allow them to be stored in the libraries only, then that *might* be acceptable to them... however, the existing capability is the exact opposite and I wouldn't want to break the previous contributor's work.

**Comment by jbhuddleston** [comment]
Then the solution to storing future development notes would be to create a new feature for that purpose only. As you say, it would behave in a manner opposite to that exhibited by the user notes but would otherwise be identical. But, to misquote you, "your intellectual property, your call" :-)

**Comment by richardwilkes** [comment]
I'm afraid this is one of those things that I will not do without SJG specifically coming in and saying they will permit it. So, given that, I'm closing it out. Should someone get an actual representative of SJG to give me the OK, I'd be happy to add such a capability.
