### ISSUE TITLE
Add rpm linux support

### ISSUE THREAD

**Issue by 1s0m0rph** [richardwilkes/gcs#219]
Noticing this has support for deb package managers, but not rpm-based. Would be hugely appreciated if this could be added in!

**Comment by richardwilkes** [comment]
I actually looked at doing just that today before the 4.18 release. However, it turns out that I can’t create rpm’s with the tool I’m using while running on the Ubuntu distribution I use on my Linux box. I’d have to setup yet another Linux box for that purpose... and I just don’t have the energy for maintaining yet another platform... especially since the moment I do, I’ll likely get requests for yet another format.

The .deb files are nothing more than ar archives that you can unpack if you can’t use them directly. Not the best experience, but certainly workable for the typical Linux user.

**Comment by gtludwig** [comment]
There is always the option to use alien, as described in:

https://linuxconfig.org/how-to-install-deb-file-in-redhat-linux-8

**Comment by 1s0m0rph** [comment]
That's fair. Thanks for the reply!
