### ISSUE TITLE
Support for Optional Specializations

### ISSUE THREAD

**Issue by Rupert01** [richardwilkes/gcs#224]
Optional Specialties (B169-170) are currently unsupported, and there seems to be no easy way of doing so by hand, due to the way defaults interact with them. Some way of setting them up in the skill's window would be great.

**Comment by richardwilkes** [comment]
You can create the skills in question. What you can't do is have the software automate the exceptions to the general rule. To use the example from the book, you can create a "Chemistry (Analytical)" IQ/Average skill with the same prerequisites as the original Chemistry skill.... and then you can alter the existing Chemistry skill to default to this new Chemistry (Analytical) skill at -2.

I don't see a good way to automate this, due to the fact that it changes the difficulty of the base skill. Unless someone comes up with a good suggestion that is workable in the code, I won't be making changes to support this beyond what is already possible.
