### ISSUE TITLE
Is there some Snap-Package/Flat-Package/Ubunt-Repository that makes update easy?

### ISSUE THREAD

**Issue by mogoh** [richardwilkes/gcs#226]
Manually updating is not fun.
Is there some repository for that?
If not, can that be a feature?

**Comment by richardwilkes** [comment]
I've considered having the software download its updates for you... however, at the moment, I've decided it is useful to have folks visit the main web site so that they can see any announcements that might otherwise get overlooked.

As for integrating directly into one of the many linux package management systems... I don't really have an interest in them, as no matter what I pick, there will be people demanding I provide something else, which is just not maintainable from my perspective.
