### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by Elunian** [richardwilkes/gcs#241]
Hello! I don't know, is this bug, or not, but this looks a bit weird. This problem sometime appears when I use sorting or open and close containers. Also, I don't know, if this need to be fixed, but decided to show you, just in case.
![113](https://user-images.githubusercontent.com/58914123/89133898-c3497200-d528-11ea-9107-87290ec68a50.PNG)
![screen3](https://user-images.githubusercontent.com/58914123/89133899-c3e20880-d528-11ea-9c83-72d5846b8d0c.PNG)
![screen4](https://user-images.githubusercontent.com/58914123/89133900-c3e20880-d528-11ea-845f-3f5375615258.PNG)

**Comment by richardwilkes** [comment]
Thanks for the report. I'm aware of the problem, but I don't currently have a solution. The issue appears whenever the scale is something besides 100%, as cumulative errors creep into the calculations, especially when font measurements are involved.

**Comment by richardwilkes** [comment]
I'm going to close this issue because the above fix solves the problem for all of my test cases. I don't have your particular file to check against, though. If you find this is still broken once you've tried it with the next release, please re-open this report and attach the file so that I can see the issue first-hand.
