### ISSUE TITLE
Display modifier values beside modifier name 

### ISSUE THREAD

**Issue by efinest** [richardwilkes/gcs#245]
Would you create an output tag that displays both the modifier and the value of the modifier beside it?

**Comment by richardwilkes** [comment]
Since modifiers aren't currently exposed in the tags at all except as notes on other things, this would require yet another sub-loop set of tags in multiple places. Certainly possible, though tedious. There is more to modifiers than just a name and a value... in fact, for equipment, there are two separate values, one for cost and one for weight. Do you expect to be able to access all of the sub-parts or just some of them?

**Comment by efinest** [comment]
This was just to also output % value of the enhancements and limitations. I wasn't worried about equipment.

**Comment by Exxar** [comment]
Weren't advantage enhancement and limitation percentage values displayed on the sheet previously? I could swear this was the case before, but I just noticed they aren't currently. If this is what efinest was proposing, I'd second the request, because I feel rather disoriented now that I can't see all of the modifier values at a glance while building powers-intensive characters.

**Comment by richardwilkes** [comment]
Yes, they previously displayed as an automatic note, whether you wanted it or not. I got a fair amount of feedback that most people didn't want it and were only interested in those type of things when creating entries (i.e. in the editor) and not when displaying them (i.e. on the sheet or in output templates), since the cost / adjustment wasn't relevant at play time.

**Comment by Exxar** [comment]
Could you add it as a configuration flag?

**Comment by richardwilkes** [comment]
Yes, most likely. Not sure when I'll get to it -- but shouldn't take much effort to just provide a toggle.

**Comment by Exxar** [comment]
Thanks!
