### ISSUE TITLE
WEight and encumberance Bug? maybe?

### ISSUE THREAD

**Issue by JawareBloodriver** [richardwilkes/gcs#259]
I'm new to this, so forgive me if this is not in the correct format and the like.

But for some reason the unequip button from the equipment isn't present. there's just the little check mark. But it doesn't seem to do anything.

So be cause of this, once I add equipment to a character, it is constantly counted as encumbrance. and even when "unequipped" it still counts as it.

I don't think the program used to do this. as i remember the feature working differently, since i used it all the time.

**Comment by richardwilkes** [comment]
Equipment was split into two lists a while back, the "Carried Equipment" and "Other Equipment". To move from one to the other, you either select and drag the item to the other list, or if the other list isn't visible (because you have nothing in it), you can also right-click on the item and the first menu entry is "Move to Other Equipment" or "Move to Carried Equipment", depending on which list it is currently in.

The checkmark you referred to is for marking whether a piece of carried equipment is "equipped", which means that any special attributes it gives (DR from armor or a skill bonus from a magic ring, for example) should apply to your character.

While posting an issue here works, in the future, you'll probably be better off asking in the GURPS Discord (there's a link to it on the main GCS site). That will likely get you a quicker response as there are lots of folks there that can help -- sometimes I don't look at incoming issues here for days/weeks due to whatever is going on in my life.

Anyway, closing this out as it wasn't a bug or feature request.

**Comment by devakm** [comment]
You mention "a skill bonus from a magic ring" here and this is exactly what
I'm trying to figure out how to do. I can't find any examples in the base
library files for magic items like amulets or rings that boost accuracy,
etc.

I'm sure that I'm overlooking something.

Where can I find an example of how to set up these effects?

Thanks!

**Comment by richardwilkes** [comment]
You can use both Features and Modifiers to achieve some types of bonuses. Mostly damage and skill bonuses to weapons, although there are a lot of effects you can do. I'd suggest, like I did above, that you go to the GURPS Discord and ask questions, as there are plenty of folks there that can answer these type of things quickly.
