### ISSUE TITLE
Export to Fantasy Grounds - Batch

### ISSUE THREAD

**Issue by TheFabulousIronChef** [richardwilkes/gcs#261]
Is there a way to batch export various GCS files to Fantasy Grounds, such as NPC/PC, instead of doing them individually? That would be really, really cool.

**Comment by richardwilkes** [comment]
Is there a reason writing a script to do so from the command line doesn't work?

**Comment by TheFabulousIronChef** [comment]
No, that would be awesome; I do not know how that would work, sadly. I'm using a Mac...is this something that is an easy script to write? I have no familiarity with that, unfortunately.

**Comment by richardwilkes** [comment]
Yes, it shouldn't be hard. I'd recommend popping into the GURPS Discord and asking if anyone can help you there. If I find some spare time, I could put something together as well, but you'll likely get something quicker on Discord.

**Comment by TheFabulousIronChef** [comment]
Just did, thanks!

**Comment by richardwilkes** [comment]
So that others that might stumble across this might benefit:

Find the folder that contains the GCS files you want to convert. Right-click it, then select Services > New Terminal at Folder. A new terminal window will open, with it already in your folder. Then, you just need to do something like:

`
/Applications/GCS.app/Contents/MacOS/GCS --text ~/GCS/Master\ Library/Output\ Templates/Fantasy\ Grounds\ PC.xml *.gcs
`

That will load all files ending with gcs (the extension for character sheets) and export them via the Fantasy Grounds PC.xml template. You can substitute whichever output template you actually want to use... but you need to either surround the path with quotes, or escape the spaces as I did, above. The resulting files will be in the same directory, but in this case, with an xml extension on them.
