### ISSUE TITLE
Little glitch on Edit Equipment Window

### ISSUE THREAD

**Issue by velteyn** [richardwilkes/gcs#265]
The add (+) image button is missing.. (It was hard to figure out how to add haha)
![Immagine](https://user-images.githubusercontent.com/1019294/94601557-f17ed000-0293-11eb-9e87-907c0466dd32.png)

**Comment by richardwilkes** [comment]
This is a long-standing problem on Windows platforms. For some reason, some, but not all, Windows machines refuse to draw that button. I've spent hours in the past trying to determine how that button is different from any other in the product with no success. Due to this, I will not be spending anymore time on this particular issue and will just chalk it up to yet another oddity of the Windows platform.
