### ISSUE TITLE
Unable to open character, "No such child: -1"

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#278]
I recently added a huge note to my character, so that I could export it to Foundry.    It saved fine, but when I tried to open it in GCS, it reported:

Unable to open "Bog.gcs"
No such child: -1

If I manually delete all of the notes in the GCS file:

	"notes": [],

Then it imports correctly (of course, minus the notes).

I have attached both GCS files.
[Bog.zip](https://github.com/richardwilkes/gcs/files/5505865/Bog.zip)

**Comment by richardwilkes** [comment]
OK, I see what the problem is. The code assumes that no single row can be larger than the page size... but your note is, which is causing some logic to break. A simple one-line fix corrects the problem, but does result in that row being truncated for display, which isn't the worst thing in the world, I guess. You can still open it up and reduce its size, moving some content to another note.

**Comment by crnormand** [comment]
Fantastic.   Glad I could help.   No real problem at all, since I can always break the text into multiple notes.
