### ISSUE TITLE
Add export key @LOCATION to Advantages, Skills and Spells output

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#290]
Similar to the @LOCATION key for the equipment list, it would be nice if we could have an @LOCATION key for elements in the other lists.   This would allow exports to maintain "container" elements.

**Comment by richardwilkes** [comment]
Rather than adding an @LOCATION key, I decided to add a @PARENT_ID for those things that can be contained. At the same time, I've removed the fake ID generation in all places where the object in question already had an ID (OK, UUID) and emit that instead for its ID. In addition, the @CONTINUE_ID key, while still allowed, doesn't do anything now, as the reasoning behind it (I believe) was to ensure non-duplicate IDs between the two equipment lists. Since the IDs should now be unique, that shouldn't be an issue.

On a side note, I'd prefer to remove @LOCATION at some point, since once @PARENT_ID is available, you *should* be able to derive its value if you really need it. I've left it for now, though, since some of your templates use it.
