### ISSUE TITLE
Ritual Magic spell levels can exceed their college specialization

### ISSUE THREAD

**Issue by trev-dev** [richardwilkes/gcs#297]
In ritual magic, spells are techniques and should not exceed their default "Ritual Magic" skill levels. If a spell is added without the appropriate specialization, it should not exceed the highest specialization at a -6 penalty.

![image](https://user-images.githubusercontent.com/28788713/108586904-04a74080-7306-11eb-922a-a4a8a288f589.png)

**Comment by richardwilkes** [comment]
Turns out this was already doing the right thing. The reason the RSL is above +0 is due to Magery 3 adding its +3 bonus to your final skill level. You can test this out more clearly by disabling your Magery 3 advantage and adding points to one of the spells -- you'll see its RSL will never go above +0, regardless of how many points you spend.

**Comment by trev-dev** [comment]
I will bring to your attention that on M200, under Ritual Magic, paragraph 3: "Spells cannot exceed the associated college skill"

Paragraph 4: also states that "Magery adds to core skill, college skills and spells." If Magery adds to the +3 to the college skills above (like Ritual Magic - Animal), then what Beast Speech is actually getting is a +6 benefit from Magery.

I feel like Paragraph 3 takes precedence here. Let me know what  you think?

**Comment by richardwilkes** [comment]
I’m not following where you’re getting +6 from. GCS is clearly only giving +3 for Magery.

Note that you could get a similar effect (+3 bonus) but have it report RSL as 3 less by having Magery give its bonus to Ritual Magic and not to spells in general. You’d have to modify the Magery advantage to do so. It doesn’t change the end maximum, but would result in no spells being above RSL+0 (assuming you don’t have some other advantage giving a similar bonus to spells, of course).

**Comment by trev-dev** [comment]
The above character's IQ is 14
Their Ritual Magic (Animal) starts at 10 (IQ-4)
They have 16 points invested in Ritual Magic (+6 levels) putting them at 16 for Ritual Magic (Animal)
They have Magery 3, that puts Ritual Magic (Animal) at 19. This is the absolute cap for all Animal spells.

We agree that "Spells cannot exceed the associated college skill", no Animal spell techniques exceed level 19. Several on the sheet are, which is really the only point I'm trying to drive across.

There was some debate on [Discord](https://discord.com/channels/228546929494065152/238823846604439553/811860816798023680) as to whether or not Magery should apply to the individual spells over and above the fact that the +3 to Ritual Magic already effectively raises the default for all of the spell techniques by 3. It kinda makes it feel like "doubling up" on the Magery bonus...but since the rules do say "Magery adds to core skill, college skills and spells" it may be safe to say that Magery may just bring techniques with high prerequisite counts closer to that absolute cap of the Ritual Magic specialization.

**Comment by richardwilkes** [comment]
No, the issue above is that your example sheet has the Ritual Magic skill set to Easy, not Very Hard as it should be. That's why you're getting a 19 skill level. It is *not* receiving a bonus from Magery.... at least, that's the only way I could recreate what I see above. Using the stock advantages & skills and an IQ of 14, 16 points in Ritual Magic (Animal) will yield a skill level of 16. Now, if you want to alter Magery to give the bonus to Ritual Magic as well, then you need to remove the bonus it gives to all spells to compensate -- because otherwise you're double-dipping.
