### ISSUE TITLE
Add Hotkey/Function that clones skills from advantage features onto a character sheet

### ISSUE THREAD

**Issue by vilobion** [richardwilkes/gcs#323]
You add a talent to a character. Talent will have numerous features giving +1 per level to a bunch of skills. Hotkey should match those skills against the library, then import those skills onto the character sheet (likely at 1 pt), preferably within a skill container named after the talent.

**Comment by richardwilkes** [comment]
That's likely not always possible, due to the wide variety of ways that the actual skill list can be specified. It also has the issue of GCS not being aware of available skills, either, since it doesn't scan your library files for all possible skills and compile a list of them for purposes such as this. It only knows what is on your sheet. Due to these two considerations alone, I'm unlikely to attempt to make such a feature work.
