### ISSUE TITLE
Libraries Don't Display User Defined Attributes

### ISSUE THREAD

**Issue by Legendsmith** [richardwilkes/gcs#340]
At first I thought they didn't contain the attributes but then I saw that it was just a display problem; libraries will display user defined attributes as ST, even though the JSON will contain the correct attribute. This is slightly confusing, and could be fixed by having them simply display the id of the user defined attribute instead.

**Comment by richardwilkes** [comment]
Yes, this is an unfortunate side-effect of allowing customizable attributes that may not exist in the global preferences. The libraries only have the global preferences to reference. Displaying the id is not appropriate, as there is nothing requiring the id to be even remotely close to the user-visible name that is normally provided for the attribute.

Where, specifically, is this causing you grief? And does it cause you grief if you actually put the relevant customizations into your global preferences?

**Comment by Legendsmith** [comment]
Ah, I hadn't put these into global settings, this is better now. I was noticing that when the settings weren't global BUT the sheet settings had QN, and one tried to place a spell in a sheet from a library that should have had 'based on QN' (or other custom attribute basically), from the files, it would just revert to based on IQ. 
(The attribute requirement definitions still worked though). This is a bit of an edge case so I suppose it's not really that big of an issue.

**Comment by richardwilkes** [comment]
I don't care for the way this works, but not seeing a good solution, either. Customizability is a pain in general, due to chicken-and-egg scenarios like this.

Lets leave this open for now, though, as I may cave and use `$id` or equivalent in some cases where it can't be otherwise resolved, even though that can be misleading as well. If you can provide a screen-shot (preferably with a circled area to highlight the issue), that would be useful for future me...

**Comment by richardwilkes** [comment]
Commit f301ecb265e9b641d5c08f007aef46780e5196de provides better handling of undefined attributes
