### ISSUE TITLE
SSRT lookup function for attributes

### ISSUE THREAD

**Issue by kaldrich001** [richardwilkes/gcs#343]
Just something that could be useful for Super-Effort attributes.

**Comment by fishface60** [comment]
Would be a lot nicer than my current approach of:
```
10^(floor(($sm+2)/6))*if(($sm+2) % 6 == 1, 1.5, 1)*if(($sm+2) % 6 == 2, 2, 1)*if(($sm+2) % 6 == 3, 3, 1)*if(($sm+2) % 6 == 4, 5, 1)*if(($sm+2) % 6 == 5, 7, 1)
```
Not least because the +2 is just a magic number to shift the progression up so 0 is 2 when the progression is 1, 1.5, 2, 3, 5, 7, 10, and it doesn't work going negative because modulo is undefined.

When I used to do this in spreadsheets It would be:
```
10^(floor($sm+2))*switch($sm+2, 0, 1, 1, 1.5, 2, 2, 3, 3, 4, 5, 5, 7)
```
In a better language I'd use an array, but it was fine.

An explicit size-speed-range lookup would cover most cases, though other approximate exponential progressions show up.

The 4-step ×1, ×2, ×5, ×10 progression shows up in Spaceships Open Space and Ultra-Tech adjust for SM rules. Usually representing increasing surface area with uniform increasing length, though for spaceship open space I'm not convinced it isn't area of the base of a dome.
The 3-step ×1, ×3, ×10 progression is ubiquitous in vehicles as the increase in weight and cost of components with size.

It's more difficult to go the other way to get size/speed/range modifiers from linear measurements.
This is mathematically correct for getting the modifier for `$qty`, but breaks down at 30 due to rounding errors, and unwieldy to use, e.g. `$qty = $hp/5` for getting the SM of a living creature, but `$qty = $hp/15` for a spaceship.
```
6*floor(log10($qty))+if(log10($qty)%1>=log10(1.5),1,0)+if(log10($qty)%1>=log10(2),1,0)+if(log10($qty)%1>=log10(3),1,0)+if(log10($qty)%1>=log10(5),1,0)+if(log10($qty)%1>=log10(7),1,0)-2
```

**Comment by richardwilkes** [comment]
Added an `ssrt` function to the expressions. It takes 3 arguments:

- The length
- The units the length is in (any of pt, in, ft, yd, mi, mm, m, km, m are permitted)
- Whether to return the size or the speed/range value (non-zero is size, zero is speed/range)

**Comment by kaldrich001** [comment]
Uh, I actually meant the other way. That's why I mentioned super-effort.

**Comment by richardwilkes** [comment]
I'm not familiar with that, as I've never played supers. Got a reference?

**Comment by kaldrich001** [comment]
Super-Effort was first (to my knowledge) defined in Powers. Check P58. In this case, what I mean is just that, e.g., if you put in ssrt(12), it would return 200. That's what I was hoping for.

**Comment by richardwilkes** [comment]
OK, will make a commit later today with the inverse lookup.
