### ISSUE TITLE
DR dividor in Equipment Modifiers.

### ISSUE THREAD

**Issue by BaHalus** [richardwilkes/gcs#346]
It would be interesting to Allow Equipment Modifier to add or change the DR divisor. I was trying to add composition modifiers for a pre-historic game and it was not possible.

**Comment by richardwilkes** [comment]
There is a bunch of stuff in equipment that can't be modified via modifiers. Sometimes, this is because the variety of data possible prohibits any reasonable way to modify the data without a human getting involved and just making the correct adjustment. Other times, its just because no one has asked and it didn't occur to me that it would be useful. I can't recall if armor divisor is in the first or second category. Unfortunately, GURPS has a lot of flexibility and therefore very inconsistent (or maybe I should call that "varied") field usage for many things.
