### ISSUE TITLE
Thrust Damage incorrect when using Reduced Swing Rules

### ISSUE THREAD

**Issue by BenjaminWashington** [richardwilkes/gcs#353]
When "Use the reduced swing rules" is turned on, thrust damage jumps from 2d+2 at ST26 to 3d at ST27. All thrust damage above ST27 is one too high.

**Comment by richardwilkes** [comment]
That calculation was added by someone else. Looking at the original article it was supposedly derived from (https://noschoolgrognard.blogspot.com/2013/04/adjusting-swing-damage-in-dungeon.html), I see no mention for how strengths above 19 are handled. The traditional table had some odd adjustments at certain higher points. The calculation I see in the code for this alternate variant also does things differently above a certain threshold. Before I make any changes here, I'd like to get a definitive answer on what the actual progression should be above values of 19 (and below 10, for that matter, since those were also left out of the article).

**Comment by BenjaminWashington** [comment]
The article doesn't address high strength, but since thrust is unchanged from the traditional table, there's doesn't seem to be any reason it would go up after a certain point. Looking at it more, it skips 3d-1 for both thrust and swing damage. Whether that was intentional or not I don't know.

**Comment by richardwilkes** [comment]
There are actually a couple of break points in the current progression. In GCS, the default calculation accounts for these oddities, but it makes applying the change suggested in the article a bit suspect for anything outside of the 10-20 range.

Ideally, the standard progression that is seen at the lower levels would just march up forever... but for some reason, Sean Punch and company decided not to do that.

**Comment by richardwilkes** [comment]
OK, I had a short discussion with the author of that blog about this and I'm going to update the code to take a literal interpretation of what is stated there. This will provide a consistent, linear ramp as high as you care to go. It does mean that thrust damage from this actually exceeds the Basic Set rules at ST levels 55+. Swing is still below the Basic Set even at 100, but will cross over at some point as well (I didn't bother to do the calculation to find out where).
