### ISSUE TITLE
Screen Tearing when hovering over certain UI

### ISSUE THREAD

**Issue by ingeanus** [richardwilkes/gcs#387]
Whenever I hover over certain UI elements (Such as the difficulty for a skill, many accept buttons, etc. There's a lot, so I'm not certain what it's limited to) the UI will end up looking like the attached images. The UI is still there and functional, you can click on where it _should_ be underneath the garbage and it will work; it seems to be purely aesthetical. Restarting solves it temporarily, but it will eventually start up once again.

![image](https://user-images.githubusercontent.com/48362206/135763277-07e3fb14-ea92-4c13-958f-0932c8f88859.png)
![image](https://user-images.githubusercontent.com/48362206/135763334-06d3d424-5095-475c-9d04-1b3549b65ec5.png)

**Comment by tsuzumiC** [comment]
I recently started to have this problem as well. I also recently upgraded my computer with new hardware, CPU, Motherboard, RAM and HD, and such made a clean windows install.
I have the same GPU.

**Comment by tsuzumiC** [comment]
Maybe this is connected? Wasn't the UI rendered with JS?
https://github.com/hneemann/Digital/issues/568#issue-752899130

**Comment by richardwilkes** [comment]
Reviewing old bug reports in other Java products with a similar issue, some claim that setting `sun.java2d.d3d=false` in the config fixes the problem, while others claim it did for a while, but then the problem came back. These are all very old reports, though, with little follow-up. You could try doing that same modification to see if it works for you.

Since I don't see the problem, I have no way to know if it improves anything or whether it just makes things worse for everyone since that disables the Direct3D graphics pipeline.

To do so, find the GCS.cfg file and add a line that reads:
```
java-options=-Dsun.java2d.d3d=false
```

**Comment by tsuzumiC** [comment]
Yeah, that seems to "fixed" it for me.

From what I can tell the bug seems then be connected to the 3D rendering and activating two different widgets, like Dropdown menus, which are almost always bugged, and tooltip will instantly produces the tearing.

I can't find where I read it but it might have something to do with repaint().

But as it only appeared now after my reinstall it feels like it might not be a software problem. But I don't know...
