### ISSUE TITLE
Support for Ritual Magic (spells as techniques)

### ISSUE THREAD

**Issue by richardwilkes** [richardwilkes/gcs#39]
From [R. William Morris](mailto:noctifer1011@gmail.com):

I use these rules for Clerics in my own GURPS Fantasy game and it'd be nice to be able to create spells that use the Ritual Magic alternative rules (B242 and Thau72).  Currently, I'm 'hacking' by creating custom techniques that are spells, but that leaves me without all the wonderful number-crunching that goes along with the standard spells.

Personally, I'd be fine with just the capability of creating my own spells using Techniques, not necessarily including a copy of each spell as a Technique in the install package.

**Comment by Maeriden** [comment]
I'm interested in this feature as well.
I could try to do it myself, but I dont know how to integrate it or which files to look at. Would you be willing to help me? @richardwilkes

**Comment by richardwilkes** [comment]
This requires code changes that may or may not be trivial -- I haven't looked into it. Unfortunately, I don't have a lot of spare time right now and this is unlikely to be worked on by me any time soon.

**Comment by Maeriden** [comment]
The following is mostly speculation since I havent really looked at much of the code, but maybe it can serve as a starting point.
I figured this can be done in two ways: adding a separate "SpellTechnique" class or modify the existing Spell class.

Adding a separate class would offer more flexibility but probably require more extensive work to be integrated with the rest of the code.
It would also require a new spell library, but I think it can be generated programmatically from the existing ones.

Modifing the existing class would require adding an "isTechnique" and (maybe, see below) a "prerequisitePenalty" fields. They could probably be fitted beside the "Duration" field in the details editor.
If a spell is marked as a technique

- Its "College" field would be the specialization of a "College" skill (e.g. Fireball belongs to the Fire college so it is associated with the skill "College (Fire)").
  - This is not a prerequisite, since Thaumatology 72 sas that ritual mages can cast spells even if they dont have points in the college skill.
  - College skill level should be capped at the "core skill" level.
- Its difficulty would be locked to H, or could be left editable for flexibility.
- Its controlling attribute would become meaningless (maybe make it non-editable and gray it out).
- Its default level would be \<college skill\> + \<prerequisite penalty\>.
  - One problem with this is that the "core skill" for magic, to which college skills default, is not fixed (the manuals suggest "Ritual Magic" or "Thaumatology"), so if a user added a spell but not the college skill (because he has not spent points on it), we cant compute the spell level.
  - The above issue can be worked around by requiring to have a 0-point college skill in the sheet, otherwise show the spell in red (as if not satisfying some prerequisite).
  - The prerequisitePenalty could be computed programmatically by walking the spell prerequisites tree. I'm not sure how complex this would be though.
- Its level would be \<default level\> + \<technique formula bonus\>.
  - Level should be capped at the associated college skill level.
- Its spell prerequisites should not cause the spell to be shown in red if they are not satisfied.
  - If they are not used to compute the prerequisites tree they could be removed.

Additionally

- Magery should give a +1/level to "core skill", college skills and spell techniques, but only ONCE (see Thaumatology 72).
  - "core skill" bonus can be added easily to the Magery Features (already there if "core skill" is Thaumatology).
  - College skill bonus can be added easily to the Magery Features (gives a skill level bonus of +1 per level to skills whose name is College and specialization is anthing and category is anything)
  - No need to add spell skill bonus as long as the spell skill level is computed after the bonus to college skill is applied.

Marking each spell as a technique is annoying but it takes only a couple of clicks so I guess it's not so bad.

P.S. I'm fairly new to GURPS so even if I double-checked what I wrote I could have misinterpreted or missed something in my analysis.

**Comment by richardwilkes** [comment]
This would definitely have to be a SpellTechnique sub-class rather than a reworking of the Spell class, just like Technique is a sub-class of Skill.
