### ISSUE TITLE
Allow Spells to have 0 (zero) cost (just like skills)

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#424]
Currently, if you put in 0 points in a Spell, it deletes the SL and RSL columns.

I know per RAW, you must put a point in a Spell to "purchase" it but it would be nice if we could "purchase" as default version of the Spell.

I ask because of my other issue (https://github.com/richardwilkes/gcs/issues/425)

**Comment by crnormand** [comment]
Of course, I found a workaround... just create a disadvantage equal to the number of spells (Spell Cost Offset):
![image](https://user-images.githubusercontent.com/8931036/156694534-1156452f-977c-41cc-95c3-1f6485adffa7.png)

So, low-ish priority.

**Comment by richardwilkes** [comment]
I'm closing this out since I don't see a way to make this practical. In particular, skills can indeed be put on a sheet at 0 points and will sometimes have a skill level associated with them -- however, that is solely because skills have defaults. Spells have no such concept, at least not per RAW, nor as represented in GCS.
