### ISSUE TITLE
Unusual DR Behavior for Non-Humanoid Body Types

### ISSUE THREAD

**Issue by Calmquist** [richardwilkes/gcs#431]
When adding the Damage Resistance advantage from Basic Set Advantages to a character with a non-humanoid body type, the DR bonus features appear to be duplicated in the UI for particular body parts. For example, Arachnoid body types appear to have multiple copies of DR bonus to the Brain while Quadrupeds appear to have the bonus to the Eyes.

I believe this to be a UI issue since JSON does not appear to show anything incorrect.

[dr_test.txt](https://github.com/richardwilkes/gcs/files/8374549/dr_test.txt)

**Comment by richardwilkes** [comment]
This is due to the fact that the UI is attempting to locate the specified location in the body type that the character sheet is using and not finding it. The popup isn't being set to anything specific, so you end up seeing it with the first entry -- in this case, Brain.

In the new version of GCS I'm working on, the UI instead adds a temporary entry that will say something like "unrecognized key (skull) for body type (Arachnoid)" so that you know what the original data was trying to do. I've already implemented this, but it is part of the rewrite to Go, so may be a while before the actual version 5 release shows up with the fix.
