### ISSUE TITLE
Skill Specializations Defaults Broken

### ISSUE THREAD

**Issue by ethomas340** [richardwilkes/gcs#432]
Skill specializations seem to not be defaulting to Any in the latest version.

Example - Guns

Guns (Grenade Launcher) has defaults to Guns -4 with no specialization entered in the skill block from the library file. My copy of GCS doesn't seem to be registering it and is not defaulting to any other guns skills.

**Comment by richardwilkes** [comment]
GCS defaults have never worked that way, unfortunately. If a skill is specialized, then you need to specify the specialization that matches for a default. I don’t recall why it is that way anymore, but at the time, there was some issue with allowing no entry to be treated as a wildcard. Things have changed a lot since then, so there may be an easy solution now.

**Comment by richardwilkes** [comment]
Looking at this briefly again, I noticed that as long as the two skills in question don't have the same name, the wildcard notion works fine. This is due to the way default chains are resolved and the need to prune out subsets to ensure they aren't revisited multiple times. Unfortunately, this is effectively an edge case that will need special logic to fix. (sigh)
