### ISSUE TITLE
Add option to allow equipped status to apply to contents of containers when toggled

### ISSUE THREAD

**Issue by Rodayan** [richardwilkes/gcs#437]
It used to be that when you opened an equipment container and clicked on Equipped/Carried/NotCarried this status would propagate to the contents (and, by extension, to the Carried Weight calculation).

I downloaded the very latest version and updated all my character sheets, only to find that in the new separation between the Carried Equipment and Other Equipment panels, this function no longer works. I'm not keen to go through every thing in my Large Backpack and turn it off.

![equipment](https://user-images.githubusercontent.com/68035683/164953721-70d9820f-094d-4590-9f96-490d546965ae.png)

**Comment by richardwilkes** [comment]
This is working as intended. Carried equipment is just that: carried. Changing its equipped status does not change that fact. Equipped only changes whether features that affect the user are applied or not (a ring that grants +1 to ST, for example).

This behavior was changed when the two lists were separated quite some time ago (years now, I think). If you want to “drop” something, drag it from the carried equipment list to the other equipment list (or right-click and chose the option to move it).

**Comment by Rodayan** [comment]
Hi, I think you miss the point of my question. The contents of a backpack should automatically become equipped if the backpack is equipped. The contents of a backpack should automatically become not carried if the backpack is ‘put down’.  The problem is in the follow-on relationship between the container and its contents.

Thanks
Rodayan

**Comment by richardwilkes** [comment]
I see. Yes, that was also changed, since I got a lot of feedback that it would be better not to keep them in lock-step. I’m willing to be convinced otherwise.

**Comment by Rodayan** [comment]
Hmmm.  How about a halfway point – a box in Options where you can turn on “equipment containers status propagation” or something? Then people could leave it off as the new default or go back to the ‘old code’.
Fair enough though! I love the program and you’ve put soooo much work into it. Well done.

Thanks again!

**Comment by richardwilkes** [comment]
Looking at this again today and I'm still not seeing something that warrants changing. If you want to alter a bunch of things at once, you just need to select them all, then hit the Toggle State menu item to switch them all at once. Shift-select the container and its contents and Toggle State gives you the same effect as before. Yes, one extra click in this case, but since the majority of feedback I had showed that people didn't want the old behavior, this doesn't seem like something I should try to optimize for.

I'd also say that it rarely makes sense for something in a pouch or backpack to be considered to be equipped (i.e. giving bonuses for being active) anyway. Typically you'd need to be wearing the item in question, not just carrying it in a pouch.
