### ISSUE TITLE
Weapon Damage, especially for bows

### ISSUE THREAD

**Issue by acrosome** [richardwilkes/gcs#449]
The calculated weapon damage does not take into account advantages like Arm ST or Strongbow, and it is onerous to change statistics to allow for them.  There is at least an easy option for bows and similar missile weapons- just edit the ST statistic of the weapon and have range and damage calculated from that.  All such weapons have to have a ST score, anyway, since bows and crossbows have to be built to a specific ST.

**Comment by richardwilkes** [comment]
This is because the advantage for Arm ST in the Basic Set library doesn't include any features to add such bonuses. That can be done. However, since this particular advantage can be selective (i.e. my right arm has +2 ST, but not my left), it was left out, since there is no way for GCS to automatically apply such constraints, since it can't know which arms are being used for a given task. If all of your arms have this, then GCS can model it just fine -- add the appropriate features to the advantage.

As for Strongbow, all that does is allow you to use a bow whose rated ST is higher than you normally could do. The bow's rated ST does not change due to this. GCS doesn't prevent you from doing exactly this. It could be argued that GCS should be checking the ST of the bow against the character's ST and flagging it in some way if you don't meet that prerequisite. If I did make it do that, I'd then need to have a way for you to add the feature of altering that prerequisite, without actually changing the ST of the bow. That is a lot of complication that doesn't seem particularly needed to me.

**Comment by acrosome** [comment]
I'm not so sure.  It seems to me that with Strongbow being a 1-point perk
EVERY archer has it.
Dean
