### ISSUE TITLE
Add "ST" option to weapon damage bonus

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#485]
There's, I think, a decent enough number of cases in the rules where a weapon's damage is based on a higher ST value than the character's normal value. In my opinion, the best way of handling this (rather than adding another limitation to an ST bonus, as I've seen suggested elsewhere iirc), is to add an option (labelled "ST", probably) to Weapon Damage Bonuses, which modifies the Striking ST value used to look up the thrust or swing value on which a weapon's damage is based.

**Comment by woefulhc** [comment]
I'll add that while Striking ST in the Basic Set Advantages library does include a -60% limitation for "One Attack Only" I have not found a way to get GCS to correctly reflect this within weapons, advantages or skills. Currently I end up manually setting the raw damage rather than leaving it based on swing or thrust.

**Comment by richardwilkes** [comment]
None of the suggestions I've heard so far (not just in this issue) can be realistically implemented, as far as I can tell.

There are a number of things that are needed:

- An ability to limit a trait (or maybe just a feature) to only a specific target. That is a tall order, as there is no guarantee that the things picked to qualify it as the target make it unique.
- An ability to add the modifier independently of the trait, so that a modifier could be created that you could drag to a trait, causing it to restrict its bonuses.
- An ability to infer what the "level" is actually referring to for leveled modifiers.

Because of this, I've taken the stance so far that it is better to just modify the weapon in question to have the correct stats than try to automate it (and make a note that you've done so, if needed). I know that's not ideal, but the GURPS ruleset makes many things very difficult by having exceptional edge cases and not being very methodical about how they arrive at things (i.e. the rules tend to be rather open-ended in many cases, which is difficult to realistically code in every possibility for).

Anyway, I'm open to suggestions... but they need to be carefully thought out and detailed, such that I can actually implement them within the constraints of the existing code base.

**Comment by rinickolous** [comment]
While it would be unrealistic to implement this with an Attribute Bonus as the base feature to which a limitation would be added, I don't see the same problems cropping up if this is implemented as an option for the Weapon Damage Bonus feature.

I believe it adequately answers your issues with the idea:
> An ability to limit a trait (or maybe just a feature) to only a specific target. That is a tall order, as there is no guarantee that the things picked to qualify it as the target make it unique.

Making sure the target is unique isn't necessary. The Weapon Damage Bonus already has fields for limiting its targets to weapons either of a specific name, a specific associated skill name, or the "this weapon" option. Further, as you know, the bonus has several other fields for limiting its targets to what the user wants. This should be more than enough for the vast majority of use cases.

> An ability to add the modifier independently of the trait, so that a modifier could be created that you could drag to a trait, causing it to restrict its bonuses.

This can be easily solved by using a Weapon Damage Bonus. The Striking ST Advantage's "One Attack Only" modifier could simply include a negation of the Attribute Bonus it gives (-1 per level or what have you), as well as a Weapon Damage Bonus, with `@Substitution Fields@` in the appropriate places.

> An ability to infer what the "level" is actually referring to for levelled modifiers.

This should not be an issue either. A levelled modifier would simply increase the ST level (for the specified weapon) by the given amount, per level of the modifier, if the "per level" option is also chosen. I may be missing something with this one, but it seems relatively simple to solve.

While I agree that it'd be unrealistic to expect every GURPS edge case to be supported, I think this one sees enough use (and would be simple enough to implement, from what I can tell), that it would be worth doing.

**Comment by richardwilkes** [comment]
I think a couple of concrete cases that I can work against would be useful. Anyone want to dig them up and outline them for me?

**Comment by woefulhc** [comment]
In thinking about this, all the uses I come up with come down to 
- A different ST is used for this *attack (mode)* than the character's listed (ST+Striking ST). 
That is an adequate description for what StongBow does. It also covers the single attack/weapon limitation on Striking ST. It also potentially gives a way for characters that have things (like Holy Might in DFRPG, or power blow) to add entries for those and have GCS calculate the correct damage. It also provides a way for Expert Backstabbing to show up in the damage in GCS.

**Comment by woefulhc** [comment]
Another use case where this comes into play is if a character is using a melee weapon via telekinesis.

**Comment by KorGgenT** [comment]
would it be difficult to apply this to range as well, since strongbow and elven bows increase range to the effective ST value?

**Comment by richardwilkes** [comment]
This was implemented in the v5.11 release as the "Rated ST" field in equipment.
