### ISSUE TITLE
Implement rounding settings for equipment weight 

### ISSUE THREAD

**Issue by Sirgoii** [richardwilkes/gcs#492]
When using modifiers for equipment, certain modifiers will modify weight by fractions like 2/3x, and modifying equipment with an integer weight will net results like attached where weights will round all the way to the millionth of a pound. 

> ![Unsightly](https://user-images.githubusercontent.com/109975617/180814512-d046dcdc-9797-4736-9a93-d7fddd8f8378.png) Absolutely unsightly.

For most games this measure of accuracy is extraneous and on my sheet it creates some awful number gore and cluttering (especially for characters who have multiple instances of equipment with modifiers). 

An option in sheet settings to decide whether to round to the hundredth, thousandth, etc. would be appreciated.

**Comment by richardwilkes** [comment]
I don't plan to add any additional controls for this. The current code intentionally does all math with 4 digits of precision, unlike previously, and therefore now only displays up to 4 digits after the decimal. I realize that's not what is being asked for here, but I'm not willing to allow the setting of arbitrary cut-offs for display, since the underlying math would still be using the full value. This would just lead to a spike in support for me as folks won't realize what's happening despite having set the option themselves.
