### ISSUE TITLE
v5 Bug (?): Sorting a table by clicking on a column header leaves the header highlighted until the sheet is closed and re-opened

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#506]

**Comment by richardwilkes** [comment]
If you're referring to the sheets & templates, that's intentional, since there often isn't enough horizontal space to add the sort indicator. Instead, I color the sorted header differently.

I'm open to other suggestions, as long as they don't involve adding horizontal space to the column or reducing the available text space in the header.

**Comment by rinickolous** [comment]
I don't really have a good suggestion for a replacement. Oh well.
