### ISSUE TITLE
v5 Feature Request: File Dialog Changes

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#512]
I'm currently experiencing an issue when opening files, in that the character sheets and other files which I use within GCS are on a disk partition mounted at `/media/`. Since GCS is not run as root, its file browsing dialog does not have access to the root directory, and thus doesn't have direct access to its sub-directories.

My requests are as follows:
- Please let users manually input the directory path to browse.
- Please allow the file dialog to follow symbolic links to directories (currently, the dialog box will not even display files which are not openable in GCS, and while this sort of makes sense, it makes file browsing difficult)
Alternatively, could you allow Linux users to use their default system file browsing dialog option?

**Comment by richardwilkes** [comment]
No, I cannot reasonably use the "default system file dialog" on Linux, because there actually is no such thing. Essentially, those come from whatever toolkit (gtk, gnome, etc) that you are using. Unlike on macOS and Windows, those aren't an actual standard that I can rely on. The only common denominator on Linux is X-Windows... and even that is less so lately, thanks to things like Wayland starting to finally become popular.

I don't think I understand the actual issue, though. Are you saying you cannot navigate to a directory that you actually have access to? Why not? In theory, to have access, you need to have read access to both the directory in question and every one of its parents.

**Comment by rinickolous** [comment]
Update: I thought this was a problem with GCS, but it turns out to just be an issue with my folder permissions. Please disregard most of this Issue.

However, I would still appreciate adding the option to type in a path to browse, instead of having to click an option in a dropdown list, then have to click around to navigate.

**Comment by richardwilkes** [comment]
I do want to make the file dialog more usable. I just haven't focused on it yet, since the other platforms make use of their native dialog and therefore I very rarely see it.

Other than being able to enter a path via typing, is there anything else that you think would make things easier?

**Comment by rinickolous** [comment]
I would be satisfied with just manual path input, though two other suggestions would be the ability to follow symbolic links, and having a "common / pinned directories" section to quickly access frequently used save locations.
