### ISSUE TITLE
Please return exporting as PNG to GCS

### ISSUE THREAD

**Issue by ArchSinccubus** [richardwilkes/gcs#535]
I use GCS in the context of pbp online play on Discord. In the servers I use it, being able to export as PNG is a super quick, super handy way to share your sheets with someone else without having to download a file to view (And also handy for mobile).

I would love to see this feature returned, please. A lot of the games I am in online use it as a means to share sheets with one another and reference them later quickly.

**Comment by AngryZen** [comment]
Yes please. I use that functionality daily.

**Comment by LillyanaKabal** [comment]
Made a Github account just to say, this is an important thing for my GURPing.

**Comment by Exxar** [comment]
Yeah, as already mentioned elsewhere, the PNG export is used in most of the GURPS Discord servers where people play games which I've been a member of during the past several years. Like, tens of different gaming groups. It is extremely practical for sharing characters because you can just see the image in Discord. With a PDF or .gcs file you need to open another program, and may not be able to when you just have your phone or are otherwise not with the device you usually use for managing characters.

**Comment by Viridianus** [comment]
Agreed on all of the above. Moreover, it helps preserve the sheet should another update make GCS formats incompatible (as it was somewhere between 4.11 and 4.30).
And while we're at it, filter by categories is also gone?

**Comment by AngryZen** [comment]
> And while we're at it, filter by categories is also gone?

https://github.com/richardwilkes/gcs/issues/534
