### ISSUE TITLE
KDE file dialog pops up behind main window

### ISSUE THREAD

**Issue by dripton** [richardwilkes/gcs#537]
At least in Kubuntu, the KDE file dialog pops up behind the main window.  This makes it invisible if you're running the program maximized; you have to think to minimize the main window so you can find the file dialog.  Dialogs should normally pop up above the calling program; most UI environments will let you pass an argument to the dialog constructor to make this happen without a lot of work.

**Comment by richardwilkes** [comment]
Hmm... this isn't actually anything I control. I don't even have access to the window it puts up -- I essentially run an external command and hope for the best, since I don't have direct access to the file dialog. If you have specific suggestions on how to work around this, I'm open to suggestions. I use the utility `kdialog` on KDE, if available. I also look for `zenity` as a backup (that's the gnome version of the same thing, albeit completely different way to invoke).

**Comment by richardwilkes** [comment]
Also, odd that it is doing this to you -- in testing on my machine (I know, famous last words), it always brought the dialog up in front, on both kde and gnome.

**Comment by dripton** [comment]
Could be some other UI setting that's different between my machine and yours.  This is mostly just a minor annoyance not a huge deal; I mostly mentioned it because it might confuse less savvy users who might not think to go hunting behind the main window for the dialog.  I'll play with the code and send you a PR if I can fix it.

**Comment by richardwilkes** [comment]
I agree 1000% percent. It just looks bad and is definitely very confusing should it happen to you if you're aren't great with computers.

**Comment by richardwilkes** [comment]
I don't see any way of fixing this since I'm completely at the mercy of the underlying OS behavior here and don't actually have any control over what it is doing. I can (and have as a fallback, should the normal route not be available) implement my own fully custom file dialog. That has the problem that on OS's that like to sandbox things, I don't get the behavior where interacting with the file dialog gives the program access to the files in question, which makes it useless in those environments, which is why it is not the default.
