### ISSUE TITLE
Unable to use control to highlight multiple things in 5.0.1

### ISSUE THREAD

**Issue by darkband** [richardwilkes/gcs#538]
Tried to use control to highlight multiple items to drag onto a sheet together, but it wouldn't let me. Shift clicking still works, but only for ones right next to each other

**Comment by richardwilkes** [comment]
The modifier you're looking for is the alt/option key. The command key on macOS will also work. I don't use control for this because it is commonly used for other things on Windows & Linux.

**Comment by richardwilkes** [comment]
So, it turns out that the conflicts that I originally changed this from ctrl to alt for was being caused by some automation software that some folks had installed. When they turned it off, the conflict went away. So... I've decided to go ahead and put this back since I don't see a strong need to support automation software that is getting in the way of normal operation.
