### ISSUE TITLE
GCS5: No External PDF Viewer Support? & Integrated PDF Viewer Suggestions

### ISSUE THREAD

**Issue by Nyksia** [richardwilkes/gcs#539]
This is more of both a question and a suggestion issue.
Is the support for external PDF Viewers completely removed or will it be added again? Or is the integrated PDF Viewer going to be a permanent replacement?

Also suggestions for the integrated viewer if it is meant to be a replacement, it badly needs the following to be viable otherwise it is in all ways an inferior solution to what was previously available:

- Ability to pan the view by holding down the mouse button.
- Ability to zoom in and out using the scroll wheel.
- Zoom level presets, i.e. Fit to the Screen, Fit Page, etc.
- Different Page Displays, i.e. side-by-side.
- Bookmarks integration.

**Comment by richardwilkes** [comment]
Yes, the integrated PDF viewer is a permanent replacement for the external ones. The external support was an experiment and it ultimately was causing too many support issues to be created, as external vendors kept changing things on me (and in many cases, users of GCS just weren't technical enough to install them properly, either, which compounded the problem).

Panning is already present via the scroll wheel. I'm open to supporting other methods, but chose the one I was familiar with in other programs. Certainly not universal, as I've seen half a dozen solutions to this.

Zoom is currently done either via the text widget in the upper left corner or by hitting cmd-minus/cmd-equal (substitute control for cmd on Windows & Linux). Again, I'm open to other methods. Things like Fit to Screen or Fit to Page might be something that can be added without too much fuss... but I'm not sure. Sometimes the relevant info isn't available until too late (i.e. having to render it multiple times, once to figure out its dimensions, then again to scale it -- not saying this is the case, but I've hit absurdities like that before).

I'm unlikely to do side-by-side page display, at least it would be a very low priority item on any list I made of things to do.

I believe I already have the bookmark information, and if so, can display that, although I'm unclear as to what the best interface for that would be.

Anyway, I'm open to most of the suggestions above, although it would be better if individual issues were created for each, because otherwise some may get lost/overlooked as others get resolved.

**Comment by Nyksia** [comment]
I'll try to write up issues for each suggestion later. So this can probably be closed.
But as far as panning with the scroll wheel, unless it doesn't work at all for me, the only thing scroll wheel does is scrolling the page up and down. 
Panning is usually being able to drag around the view both vertically and horizontally, so either I'm misunderstanding, or for some reason the panning with the scroll wheel doesn't work for me.

**Comment by richardwilkes** [comment]
It does require that you either have a mouse capable of doing horizontal scrolling (mine, for example, has a mouse wheel for both vertical and horizontal movement) or that you press and hold the shift key while using the primary scroll wheel, in which case I turn it into a horizontal scroll... at least, I do that on macOS -- I'm not 100% sure I extended that to the other platforms. Worth trying, though, in the meantime.

**Comment by Nyksia** [comment]
Separated all the suggestions into #540, #541, #542, #543 and #545
