### ISSUE TITLE
Add alternate page display modes for the integrated PDF viewer

### ISSUE THREAD

**Issue by Nyksia** [richardwilkes/gcs#541]
While something like Side-by-side view is probably very niche, I think something akin to 'Continuous' view would be a nice feature to have. A means of changing the page by continuously scrolling past the page's beginning or the end.
Don't know how difficult it would be to implement visually, to display the next and previous pages as the user scrolls by, but it shouldn't be too difficult to just make the extra scrolling act same as if you were to press the button to change pages at the very least.

**Comment by richardwilkes** [comment]
Given the way scrolling is handled in the UI framework, there really isn't a good spot to insert such logic that doesn't effectively require rendering the entire document first and having one very large space that is then scrolled. Due to this, I'm going to close this out as something I'm not willing to do.
