### ISSUE TITLE
GCS5 Suggestion: Allow the User to configure Scroll Wheel key combo in the Integrated PDF Viewer

### ISSUE THREAD

**Issue by Nyksia** [richardwilkes/gcs#543]
Some people may be used to different ways of Zooming In and Out in apps, so it would be nice to include the ability to change what combination of key allows zooming in the Viewer.

**Comment by richardwilkes** [comment]
Due to the inevitable conflicts users would cause by selecting something that overlapped with other functionality, I'm unwilling to allow this particular thing to be changed. Using alt/option and the mouse wheel to change zoom level with the mouse doesn't seem like a burden to me and there are many other ways to change the zoom level as well... not to mention you can always just use an external PDF viewer if it really bothers you.
