### ISSUE TITLE
GCS5 Suggestion - Allow for use of external PDF reader as in previous versions

### ISSUE THREAD

**Issue by knownexus** [richardwilkes/gcs#549]
There are features in external PDF readers which would be very useful, and it's nice top be able to have the PDFs open on a different monitor
So it would be useful to be able to opt to have an external PDF reader rather than an internal one

**Comment by Nyksia** [comment]
Something I'd like to add, since I very much liked being able to use my own PDF app of choice to use.
The previous version used predetermined options for PDF apps, which is reasonable considering each supports command-line functions differently, but I _think_ it relied on default install locations?
It would be a good idea to prompt the user to select the .exe of the picked PDF if the feature were to be returned, so there would be no reliance on that at least.

At worst case, could possibly allow users to provide their own command patterns for GCS to use to open a specific page in external PDF Viewers, as a bit more of advanced user feature? That way there would be no need hassle over every single PDF app being compatible if they change how commands are written out.

Granted I am taking my reader of choice, Foxit Reader, as example on how it opens PDFs via command-lines, so I don't know how other apps do it.

**Comment by richardwilkes** [comment]
I'm adding the ability to set an arbitrary command line to use for PDFs instead of the internal PDF viewer for those that want it. I will not provide *any* support for this -- you're completely on your own, as I have no interest in helping people use the command line properly.
