### ISSUE TITLE
GCS5 UI Suggestions: Trait editor behavior

### ISSUE THREAD

**Issue by Sorenant** [richardwilkes/gcs#567]
Hello, I had previously opened a ticket suggesting some changes to the UI to improve user experience and was asked to break them down into individual entries. Here's the second one:

Until version 4.X, whenever I opened a trait editor, the tool would automatically select the trait name (see this [picture](https://i.imgur.com/LFd9DDr.jpg) for reference) and I could immediately change it then press Enter to confirm/close it. On version 5.1, both behaviors are gone, slowing down the editing flow. Would it be possible to bring those back, in particular Enter key to apply/confirm/close the editor?

**Comment by richardwilkes** [comment]
Adding focus to the first field is reasonable. I'm less certain about allowing the use of enter/return to commit anything, since that key is also used when editing any field capable of multi-line content.

I could see some hybrid approach, though, where perhaps the command key for your platform in conjunction with the enter/return key could be used to hit that button. Would that be workable? If so, how do you think I should clue people in that they can do this? Just a tooltip on the commit button?

**Comment by Sorenant** [comment]
I'm not sure if it's possible but I find the way it behaved on 4.37 was reasonable: On single line fields (eg name), Enter would apply and close the window but on muli-line fields (ex notes) it would simply create a new line.
Anyway, I see you already made the changes to the code, thanks!
