### ISSUE TITLE
Windows Defender prevents download of 5.1

### ISSUE THREAD

**Issue by sethdodson** [richardwilkes/gcs#572]
Hello, I am submitting an issue here as per the stated preference on the discord channel. 

Windows Defender seems to think that Script/Wacatac.H!ml is present in the zip file containing GCS 5.1. As a consequence, it blocks the download.

**Comment by richardwilkes** [comment]
There is nothing I can do to change the behavior of Windows Defender other than spending money to buy a Microsoft developer certificate so that I can sign the binaries. I will not be doing that. If you don't trust the download, you are welcome to build it yourself. I know, not the answer you'd prefer, but I'm unwilling to spend money on something that I give away for free and is essentially an unnecessary tax from Microsoft.
