### ISSUE TITLE
Cannot create zero-cost trait with levels

### ISSUE THREAD

**Issue by BitBlitObviMormon** [richardwilkes/gcs#574]
The new version 5.0 and newer removed the ability to have zero-cost traits with levels. It is now impossible to have racial templates with features like increased SM or born biter because those traits cost zero points per level. Existing templates that use those traits now have the level removed from the trait when saved. It is still possible to have zero-cost levels in 4.0 versions

**Comment by richardwilkes** [comment]
You are correct that creating leveled traits when those levels cost 0 isn't possible anymore. They don't seem to make sense, which is why I've removed them. If something costs 0, then why not just have an infinite level of it? The mention of Born Biter is odd, in that it is not a leveled trait, per the book. SM is typically set directly on the SM field itself or if coming from a racial trait, set to a specific value and isn't something you level, either.

Anyway, as I've stated, I'm failing to see the need. Feel free to provide convincing argument in favor of making it slightly more effort to use leveled traits (slightly in that you will then have to check a box to enable the ability and then set a value per level, rather than just setting a value per level).

**Comment by richardwilkes** [comment]
I'm closing this, but feel free to re-open and post your argument for doing this.

**Comment by BitBlitObviMormon** [comment]
Born biter (in Martial Arts p. 115) is indeed a leveled trait. Each level (up to +3) of born biter increases the creature's effective SM for biting but also gives other creatures a bonus equal to the level of born biter to strike the creature's mouth or head. It costs zero points because each level has a drawback in addition to the buff.

**Comment by richardwilkes** [comment]
Hmm... I hate that they redefine traits in books to be different. They should really just come up with a new name instead of breaking old rules. Oh well.

Given this and a few other folks that have presented their case for it, I've relented and will be adding a way to toggle the per-level ability again. I don't like it, but I can see that the GURPS authors have made it necessary.
