### ISSUE TITLE
Trait editor doesn't open in best spot

### ISSUE THREAD

**Issue by crnormand** [richardwilkes/gcs#588]
Sorry, it was just easier to show (I'm in the middle of making another video... based on GCS 5).  Its only 59 seconds long.

https://user-images.githubusercontent.com/8931036/197262433-217a6374-0504-4639-ab35-3679e7f64e41.mp4

**Comment by richardwilkes** [comment]
What's happening here is that each basic type of thing opens into its own group. The editor is actually opening up to the far right. This is splitting the tab space that was already on the far right, but since the editor wanted a lot of horizontal space, it consumed it all, forcing the existing list down to just a divider bar (you'll notice that you now have two of them between the sheet and the editor instead of just one -- that extra one is the former list view compressed down to nothing). This happens because the first time in, the dividers haven't been moved, so the program takes it upon itself to size-to-fit for the new thing coming in. Once you've manually sized them, however, it will try not to do that any longer.

I'm not clear on how I can make this better that doesn't make something else worse (or potentially significantly worse). I'm open to suggestions, but as you are aware, what is easy for a human to reason about can often be rather challenging to get the computer to do the same thing.

**Comment by crnormand** [comment]
Understood.   I just wanted to show you, and so long as you knew it was happening (and why), I'm fine with it.   I only found it because I recording on a smaller screen, and I had the zoom set to 170%.    I never noticed it in the normal usage.   BTW, when I cut together the video... I will upload a pre-release for you to check out.   It won't have my pre- and post talk... it will just show me using GCS5.

**Comment by ndrwstn** [comment]
I wouldn't suggest this issue is closed. The choice to always open to the far right is sub-optimal at best. New windows (#560) was best, but if that's not possible, then we need either a way to select where the tab appears or have it remember where you last put the tab. With the new tabs, I always split the character sheet "down" (split horizontally in the tmux-sense) and have the trait editor below the character sheet. If it could remember this, that'd be fine, but it always opens to the far right.

**Comment by richardwilkes** [comment]
I agree this isn't great. Until someone comes up with an implementable strategy however, nothing will happen. I've tried a bunch of different ways to do this and all of them fail to be great under many circumstances.

Also, "new windows was best" is purely subjective. Yes, there are folks out there that would prefer that. There are plenty that don't, as well. Given the issues with dialogs on some platforms, I'm currently trying to avoid them where possible.

**Comment by ndrwstn** [comment]
Subjective or not, it is how most OSes implement these type of detail edits. I understand the technological problems you identify in the other issue (that windows aren't popping to the foreground) so I understand the change. In the meantime, can you re-open this issue from "closed" (I'm not the owner) or do you want me to open a new issue for this?

**Comment by richardwilkes** [comment]
Sure. Didn't realize it was actually closed.

**Comment by YeshuaAgapao** [comment]
![GCS_EditorPane1](https://user-images.githubusercontent.com/73035795/199143130-68e04e66-6400-426d-b673-124ce815b3e0.png)
![GCS_EditorPane2](https://user-images.githubusercontent.com/73035795/199143149-ac782fc0-228d-42f6-a173-76425973e33d.png)

First picture is where I want the editor panes to go.  Second picture is where they end up.
High resolution screen.

Designate tab groups to receive new detail editor tabs?

If all else fails, just make them dialog boxes again. I'm sure some users won't like that, but that is what preferences are fore.

**Comment by richardwilkes** [comment]
Given that you can now set detail editors to open in their own window, I'm going to close this, since I don't see a good way to improve this that isn't hideously complicated and likely to cause more problems than it solves.
