### ISSUE TITLE
External PDF Viewer not usable on Windows

### ISSUE THREAD

**Issue by Nedorus** [richardwilkes/gcs#595]
### Environment
GCS Version: 5.3.0
Windows Version: Windows 11 (latest)
PDF Viewer: SumatraPDF or Adobe Acrobat (latest versions)

### Steps to recreate issue

1. set path to PDF viewer by copy-pasting from windows explorer
2. save pdf in a location containing spaces
3. set page reference in GCS to pdf location
4. try to open pdf via page reference in gcs

=> PDF viewer will not open

### Manual solution Step 1
Replace all `'\\'` in the path to pdf viewer by `'/'`

=> pdf viewer will now open but PDF will not load (SumatraPDF briefly shows error message that file `"**C:\Program Files\**[...]"` cannot be found.
Note that the the path shown seems to start with `"C:\Program Files"` even though the pdf to be opened is on `"D:\..."`

### Manual solution Step 2
1. move the pdf file to a location without spaces in the path (e.g. D:\Rulebook_Characters.pdf)
2. point the page reference in GCS to this file
3. manually replace all `"\\"` by `"/"` in the config file (gcs_prefs.json)

=> pdf will now open (when adding $page and $file correctly it will open on the correct page as well

### Observation
it seems that there are two separate problems here

1. When the path to the PDFs contains spaces `' '` then the command line interprets the individual parts as separate arguments to the pdf viewer call. Since there is no driveletter to the last part the "C:\Program Files" is pre-fixed as this is where the command line call is made from (probably one error message is shown per 'part' but too fast to see?). Idea: enclose the path and file name in double quotes when calling on the command line
2. The "\\" seem to be falsely interpreted /not correctly escaped between entering in UI -> storing -> reading -> calling the command line.

**Comment by richardwilkes** [comment]
As I stated when I added this feature, I do not plan to do any specific support for the command line option, precisely because it can be fraught with issues and I just don't have any interest in hand-holding for it.

As for the spaces issue -- yes, when you provide the command line in GCS, you should definitely put some quotes around the $FILE arg if you think they are needed. I don't do this for you automatically, because the rules on each platform can be slightly different and fixing it for one use case is highly likely to break it for another. You are in full control of said command line, so it is up to you to enter whatever is necessary for your specific needs.

The backslash stored in the json is there to follow the json rules for how to escape strings stored within the value. When loaded, things like `\\` turn into `\`. Unfortunately for Windows users, their odd path separator (odd in the sense that all other OSs use `/` and use `\` for escaping things) causes problems. Since Windows will recognize `/` as a valid path separator, I'd recommend using those for any paths you specify. The command line parser I'm using probably uses `\` for escape as well.

**Comment by richardwilkes** [comment]
Note: I am willing to accept Pull Requests that address issues, but it has to be clear in those PRs that whatever change is made will work on every platform.
