### ISSUE TITLE
Parry with specialization

### ISSUE THREAD

**Issue by ssveter1** [richardwilkes/gcs#605]
Parry with specializations like Parry (Rapier).
or the ability to fill the box next to parry.
![image](https://user-images.githubusercontent.com/10831302/202548845-7a5d38c7-7c4e-4677-875d-ec7ac7d709c8.png)

**Comment by richardwilkes** [comment]
Specialization doesn't actually make sense from a GCS data point of view. What would that field actually be checking against? There is no parry skill. The weapon name might be an option, although that can be very generic and difficult to pinpoint, not to mention it becomes confusing due to weapons being attached to a wide variety of sources.

Anyway, what's the reasoning for needing this?

**Comment by richardwilkes** [comment]
Lacking a response, I'm closing this out.
