### ISSUE TITLE
Incorrect AppData subdirectory use

### ISSUE THREAD

**Issue by outofnamespace** [richardwilkes/gcs#612]
From my installation: 
..\AppData\com.trollworks.gcs\gcs_prefs.json
..\AppData\Logs\com.trollworks.gcs\gcs.log

These should be in ../AppData/Roaming or ..AppData/Local.

I found this, which is about Vista and XP, but nothing has changed since then.
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc766489(v=ws.10)

"Windows uses the Roaming folder for application specific data, such as custom dictionaries, which are machine independent and should roam with the user profile. The AppData\Roaming folder in Windows Vista is the same as the Documents and Settings\username\Application Data folder in Windows XP."

**Comment by richardwilkes** [comment]
That document is rather poor at telling me anything useful. I definitely do not want any sort of "roaming" data, since that will just lead to data being incorrectly overwritten in many cases. It isn't clear why I'd want to push any data down into the "Local" or "LocalLow" folder. In fact, it mentions the LocalLow folder but doesn't say what it is for at all. It does have some text that seems to claim that the Local folder has something to do with a Profile -- I don't want GCS's data associated with anything Windows-specific and certainly not some Profile that some external tool might decide it should mutate in some fashion.

So... changing the location isn't hard for me... but until I see something that actually gives me a good reason to change something that seems to work fine, I'm unlikely to do so.

**Comment by outofnamespace** [comment]
A good policy to work by. Finding tech sites that babble on about this sort of thing is easy. Finding the information in MSDN is not. I will see what I can find.

In general ...
roaming is for stuff that gets copied to a server and can be accessed by any system anywhere that the user logs in. that, of course, assumes they are part of some domain/active directory network. if the user isn't, then it just sits there, like local. roaming is by far the most commonly used location, because "why not".

local is for everything that won't be copied to a server

locallow is for anything that isn't copied to a server and has very low level security. temp files or a browser cache, for example

**Comment by outofnamespace** [comment]
Everything I am finding, current and long ago, keeps pointing back to this
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-vista/cc766489(v=ws.10)

Apparently, Windows 10 had a flaw in one of the updates about 4 years ago that causes Local to get synced to roaming profiles. Considering that could easily be GBs of extra data per user, there is quite a bit of "commentary" about it.

This document deals with updating roaming users from XP to Vista and the new folder structure.
From that document I find:

In the directory conversion table 
"AppData | Not applicable | Default location for user application data and binaries (hidden folder)"

**This is key. They don't outright say it, but the implication is that appdata needs to be in sub-directories.** 
"Windows Vista also has changed the Application Data folder structure. Previous user profiles did not logically sort data stored in the Application Data folder, making it difficult to distinguish data that belonged to the machine from data belonging to the user. Windows Vista addresses this issue by creating a single AppData folder under the user profile. The AppData folder contains three subfolders: Roaming, Local, and LocalLow."
The very reason I noticed this is because when I checked the path settings, GCAs two directories at the AppData level stick out like a sore thumb.

About Local*
"Windows uses the Local and LocalLow folders for application data that does not roam with the user."

About Roaming
"Windows uses the Roaming folder for application specific data, such as custom dictionaries, which are machine independent and should roam with the user profile."

I don't have MSDN access so I'm afraid this is about the best I can do with just duckduckgo and google on my side.

On the bright side, at least it isn't that Linux Filesystem Hierarchy Standard mess.

**Comment by outofnamespace** [comment]
PS: Based on your comment, I would suggest AppData/Local

**Comment by richardwilkes** [comment]
Thanks for digging further into this. I've done a bit more as well and am willing to move things down a level inside a "Local" dir. I'll unfortunately also need to have the code try and auto-detect that you used to have data in the previous location and automatically move it for you, since otherwise Windows users will lose all of their settings -- which is easily recoverable, but I've found the vast majority of Windows users have real problems understanding how to deal with these directories or anything that has to do with a command line.

**Comment by outofnamespace** [comment]
I wouldn't consider this urgent, since clearly I'm the only one that noticed it.

For my 2 cents, I would suggest:
```
AppData/Local/com.trollworks.gcs/<whatever>
AppData/Local/com.trollworks.gcs/Log
```

Windows OS and apps don't store logs in this sort of manner. They have this whole bloated event view thing. The Log directory would be unique to you so you might as well put it your directory to make it easier to find.

**Comment by richardwilkes** [comment]
Implemented for the next release
