### ISSUE TITLE
incorrect feature location list

### ISSUE THREAD

**Issue by outofnamespace** [richardwilkes/gcs#617]
1) Add three eyes to the human body type.
2) add new equipment
3) add feature
4) "gives a DR bonus of"
5) under the location only the last eye on the list will be there

reorder the eyes and still only the last one

**Comment by richardwilkes** [comment]
Please attach a file illustrating the problem. I suspect it's because you've used the same id for each eye entry -- when you do that, they collapse to a single choice name, since that's what you've actually defined. The multiples in that case are purely for rendering on the table, presumably because you gave them some slots for a roll to choose them.

**Comment by outofnamespace** [comment]
You are correct, my bad
