### ISSUE TITLE
item uses increment/decrement

### ISSUE THREAD

**Issue by outofnamespace** [richardwilkes/gcs#631]
Increase past maximum and it decreases by one. Decrease past 0 ... works. It should probably stop at 0.

**Comment by outofnamespace** [comment]
In the editor the item used count does turn red. But maybe that should also happen in the equipment list?
On exiting the detail editor, the use count goes to 0.

**Comment by outofnamespace** [comment]
this happens when the editor is open.

when the editor is closed, Increase disappears for the context menu when the max is hit.
the number still goes negative on decrease

**Comment by outofnamespace** [comment]
if I have two with three uses, shouldn't the max uses also be extended? It remains at three
if i then drop one, the uses remains at 3. this might be better served as a group of items in a container, one each

**Comment by richardwilkes** [comment]
re: qty factoring in... no, I explicitly have no intentions of doing that, since it can be very confusing as to what it should actually do -- and everyone I've asked has a slightly different interpretation of what they would expect. If you want multiple things with uses that you want to track individually, make separate instances of them. That's the same answer I have for those that use a quantity other than 1 for containers and then expect to have the ability to individually deplete the contents. It just isn't reasonable and everyone has different expectations.
