### ISSUE TITLE
Markdown undo goes back to file opening

### ISSUE THREAD

**Issue by outofnamespace** [richardwilkes/gcs#636]
1) open markdown file
2) make change
3) save
4) undo

The undo menu option takes the markdown back to the point it was opened, rather than the last save or last change. On a long edit, that can be major and unexpected.

The current solution is to close and not save, then open back to the last saved.

**Comment by richardwilkes** [comment]
I agree that undo for the editor fields does not work as expected and never has. They are all-or-nothing for the entire contents since the last commit (where commit means different things depending on the context).

Saving is not an undo point for anything, however. It can often coincide with an undo point, just because of the sequence of events leading up to it, but saving itself is not meaningful for undo state management.

Anyway, the solution is to actually implement state change tracking at a much lower level than it is today. Not sure when I'll get the energy to tackle that.
