### ISSUE TITLE
local library path selection won't select a directory

### ISSUE THREAD

**Issue by outofnamespace** [richardwilkes/gcs#637]
1) Add new library
2) enter name
3) enter any random string for repository (it is required but doesn't seem to serve a purpose for local libraries)
4) select the path folder icon to open a directory browser
5) select a folder
6) Select Open

It will open the folder in the browser, rather than select it. A file can be selected, but the filename is included in the Path. If the filename is not removed, the library will not work right. If it is, the library works fine.

**Comment by richardwilkes** [comment]
Since I happen to know who you are and that you're running Windows, it isn't a problem right now, but in the future, please specify what OS you're running on whenever reporting something that might be related to the OS -- and anything having to do with the file or directory browser is definitely very OS-specific.

**Comment by outofnamespace** [comment]
probably doesn't matter to the win api, but it is windows 10

**Comment by richardwilkes** [comment]
The issue was the use of an older set of APIs that didn't actually support the directory selection mechanism I was trying to use. I've now updated the code to use the newer way of doing things on Windows.
