### ISSUE TITLE
Application launching but also not 

### ISSUE THREAD

**Issue by NaCley** [richardwilkes/gcs#638]
When i got to open a character sheet or just launch the program nothing comes up.  Task manager it says it is running as a background process but that is it.
I've uninstalled and reinstalled the latest version and it opened after I extracted the file and ran it, but after i closed it and tried to reopened it the same problem happened.

**Comment by richardwilkes** [comment]
Since you said "task manager", I'm going to assume you're running on Windows.

First, use the task manager to force any currently running GCS instances to terminate.

Next, open a command prompt and use it to change directory to wherever you have installed GCS, then type this into the command line: `.\gcs -h`

That will just show the options available to you, along with a line that starts with "Settings path:". Please attach a copy of that file to this bug report (you may need to zip it before GitHub allows you to attach it). Once you've done that, remove the file.

Try double-clicking GCS to launch it again to see if it now works. If it does, quit and launch again to verify it will work a second time. If that also works, then you had a corrupt settings file and I'll take a look at what you've attached to see if I can figure out why.

If that didn't work, then return to the command prompt and run this `.\gcs -C` and copy and paste any output that is printed on the command line into this bug report.

**Comment by richardwilkes** [comment]
Oh, when you use the first command to find the Setting Path, there will also be a path listed for the log file. Please attach a copy of that file to this bug report, too.

**Comment by richardwilkes** [comment]
(all of the above assumes you are running the GCS v5.5 or later)

**Comment by richardwilkes** [comment]
Since you've not responded, I'm going to assume you found a solution and that there is nothing I need to look at. Feel free to reopen and attach the relevant info if that's not the case.
