### ISSUE TITLE
GCS is not doing auto-hyperlinks correctly

### ISSUE THREAD

**Issue by YeshuaAgapao** [richardwilkes/gcs#648]
##### High Pole Lion Dancing
Not a thing for the risk-averse. High pole lion dancing performers are almost entirely under-25.
* Dancers practice traditional Chinese lion dance on poles in water: https://www.youtube.com/watch?v=b8XQZYVrjlQ
* Chinese performers practice lion dance on poles in water: https://www.youtube.com/shorts/wVswq7KZOoI
* Chinese New Year 2019 Lion Dance, Hong Kong: https://www.youtube.com/watch?v=Bs0GuU0cUtw
* DANGEROUS Lion Dance Gets GOLDEN BUZZER On Myanmars Got Talent 2019!: https://www.youtube.com/watch?v=ZjzhOu_JPGM
* Twin Lion Dance on High Poles: https://www.youtube.com/watch?v=KqoNw66PAdI

Only https://www.youtube.com/shorts/wVswq7KZOoI actually goes to YouTube when clicking on the auto-generated link.  The other links open windows explorer in the 'documents' folder (likely a default location).

**Comment by richardwilkes** [comment]
All of these links work for me just fine using macOS. That means Windows (as usual) is doing something odd with the command line when asked to open the given URL. It probably doesn't like the embedded `?` and needs it to be escaped in some way.

This will have to wait until I have my Windows box available to try and divine what idiotic things Windows is doing this time around... (sorry for all the derision around Windows -- I'm just getting very tired of it constantly being the problem child)

**Comment by YeshuaAgapao** [comment]
ok cool

**Comment by richardwilkes** [comment]
After much experimentation, the problem seems to be that the `explorer` command (which I used to open URLs on Windows) would fail whenever a URL parameter was present (most likely the ? in the URL was causing this), but only if executed via another program -- i.e. launching it directly from the command prompt would work, but executing the exact same thing from another program would fail. (sigh)

So, switched back to using the older method of doing this on Windows, where you start a command prompt and pass it the `start` command instead. Less ideal, since this method also puts up a command prompt window temporarily, but at least it seems to be working now.

Will be in the next release.
