### ISSUE TITLE
Feature Request: Altered Calendar Functionality

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#652]
Not sure if this is already possible since I have not tested, but I doubt it is.

I am trying to implement the Traveller 3rd Imperium calendar, and suspect I will run into an issue.
The calendar has 7 (technically 8) weekdays. I say "technically", because the first day of the year "Holiday/001" is the only day of the year with its weekday. The other 364 days use the other 7 weekdays. Is the implementation of such a calendar possible with the way the format currently works? And if not, could it be changed to accommodate?

**Comment by richardwilkes** [comment]
You're right, that's not supported.

I also don't think it is terribly practical in a general sense, since the names of the week days are inherently orthogonal to the days of the year themselves. I'm assuming the designers of this game did this solely because they wanted the days of the week to always be on the exact same calendar day for any year -- which is the case with a 7-day week, 52-week year calendar -- but then they also wanted it to match our real-world 365-day year (well, not counting leap years, anyway).

Anyway, while I can see ways to handle it, I don't know that I'm interested enough to actually do this. Are you sure you can't tolerate having it use a normal day of the week progression? The calendar support does handle arbitrary holiday day(s) that don't belong to a given month by virtue of putting them into their own "month", which is something I've used in my own games where there are 4 festivals throughout the year that last for a week each and aren't part of the regular months.
