### ISSUE TITLE
Incorrect formatted exec path in .desktop file (Linux)

### ISSUE THREAD

**Issue by Stennsen** [richardwilkes/gcs#667]
Setup:
- OS: GNU/Linux (Fedora Silverblue)
- Desktop: Gnome 43
- GCS Version: 5.7.1

The Issue:
I noticed, the automatically generated `com.trollwork.desktop` file has formats the path wrong if it is newly generated.
The Path in `Exec` has incorrectly formated Spaces in my original file (generated by GCS) the entry looked like this:

```
Exec=/var/home/stennsen/Pen and Paper/GURPS/Software/gcs-5.7.1-linux/gcs %F
```

This way Gnome doesn't recognize the .desktop file.

This can easily fixed by prefixing a Backslash to each Space:

```
Exec=/var/home/stennsen/Pen\ and\ Paper/GURPS/Software/gcs-5.7.1-linux/gcs %F
```

But if you manually changed it and then start GCS, this file gets overwritten by GCS. Maybe it would be also better to not always regenerate the file but check whether this file already exists. This way users can keep their customizations, e.g.: A Custom Icon or add custom categories

**Comment by Stennsen** [comment]
I can also resolve the issue with the falsely generated path if someone tells me, where the script is located :)

**Comment by Stennsen** [comment]
I looked a bit into where it is located:

https://github.com/richardwilkes/gcs/blob/b6e458cac78c5cf9225beeee2e1bf410ce20d8ad/ux/platform_linux.go#L61-L81

just putting parenthesis around the execPath in line 76 should also work

**Comment by richardwilkes** [comment]
Thanks for digging up the exact spot. I'll fix this once I get some spare time -- that's just been in short supply the last couple of weeks.

**Comment by richardwilkes** [comment]
So I had a bit of time this morning while waiting for something else and updated the code to fix this... however, now in testing I'm finding that -- at least on my Ubuntu 20.04 system, which I use to build GCS -- no changes I make to the desktop file are noticed by the system. It completely ignores them and continues to use the original values. Any ideas as to why this is? I know there is a `desktop-file-install` utility that may fix this, but I don't want to have to rely on it actually being present on installations.

**Comment by Stennsen** [comment]
I'm not sure myself, I can compile it myself tomorrow and try to check how it actually works.

Do you mean the file didn't get changed, after editing the code and then executing it? Or is it more like your desktop does not list the Application in the Overview?

**Comment by richardwilkes** [comment]
The file gets changed just fine, but if I then try to launch it with the desktop manager, it wants to use the old path that the file contained from my last release. I was testing by moving the GCS executable to a new dir that had spaces in its path, running it once to get it to regenerate the desktop file with the updated path, then trying to open it with the standard desktop app launcher thing (sorry, don't recall what that is called). Looking at the logs, I can see it fails because it is still looking for GCS in its previous location.

**Comment by richardwilkes** [comment]
I now remember that I had this problem in the past and it turned out that -- at least on some systems, like my Ubuntu one -- changes to .desktop files were often ignored until you log out and log back in again. There is likely an Ubuntu-specific way to correct this, but I'm not really interested in distribution-specific fixes, so lived with the need to log out and back in for the update to work.

**Comment by Stennsen** [comment]
I'm glad you found the issue! :)

But yeah, sounds pretty annoying with having to log out on Ubuntu, I don't use it myself so I don't have any idea how it could be solved in general. Just living with this issue is probably the way to go :/   As far as I know, I don't have this problem on Fedora, it always uses the newest .desktop file
