### ISSUE TITLE
Allow mapping to URLs (and not only to local files)

### ISSUE THREAD

**Issue by mfilz** [richardwilkes/gcs#670]
Feature request:
The mapping for page references currently allows only for local files. I'd like to allow the mapping to reference URLs as well, as I tend to store my PDFs on a file server. This would probably require some kind of placeholder for the page number in the URL, as access to specific pages is not uniform.

**Comment by richardwilkes** [comment]
You can already put a link into the page reference field (and have been able to for many releases now).

**Comment by richardwilkes** [comment]
To be clear: this has nothing to do with page reference mapping preferences. You literally place a full link in the page reference field, say `https://gurpscharactersheet.com`

**Comment by mfilz** [comment]
I wasn't aware of that, but that's not quite what I had in mind...
You'd have to do this for every single item with a page reference, which is, while technically possible, impractical to the point of being unusable. I was talking about the use case where your Book PDFs are actually located at an URL.

**Comment by richardwilkes** [comment]
Direct URLs are really only useful for short works where you can have a chance at finding what you're looking for quickly. That, or using URL anchors to allow jumping to specific parts, which is definitely possible, but generally doesn't work with PDFs. Anyway, I'm not going to add something like what you're asking for since opening to specific pages in PDFs via a browser -- while possible in some specific configurations -- is not generally workable without extra intervention on my part, which I'm just not going to do again. The last time I went down that route, I ended up hitting an endless series of edge cases that broke things for specific people and their configurations -- it just isn't worth the headache.
