### ISSUE TITLE
Back-conversion

### ISSUE THREAD

**Issue by Viridianus** [richardwilkes/gcs#682]
There are currently ways to convert older character sheets, libraries, etc. to newer ones. Can something be built to back-convert (even if preliminarily, with potentially lost features) sheets to older versions? Tried to search for such a request but found nothing. Preferably (but not necessarily) without using a command line or anything like that - a prepackaged thing that takes a file and returns a 4.x file.

(Specific use case in mind is converting 5.x back to post-4.37 4.x - although I did waste quite some time with converting between different 4.x versions. Windows.)

**Comment by richardwilkes** [comment]
What’s the motivation for such a thing? There would have to be significant benefit for me to consider spending any time at all on such a task.

**Comment by Viridianus** [comment]
Motivation is currently sticking to using pre-5.x versions of GCS. Given that 4.x and 5.x are fairly different (including visually), I do not expect to be alone in that.

(Although I do take the chance to say that I very much appreciate the fact that, judging by FAQ, at least forward-conversion is handled automatically this time…)

**Comment by richardwilkes** [comment]
This isn't something I have any interest in doing. It would be a fairly significant undertaking, but certainly not impossible. Those that want such a thing will need to create it themselves, though.

I'd be interested in hearing what the reasons were for not wanting to use the newer releases. I think I've heard two from others so far:

1. They want the modal dialogs back when editing. For small screens in particular, this is a valid criticism. I currently avoid modals as much as possible right now because each OS I support has quirks where *sometimes* the OS ignores the software when instructed to create a new window in front of others (and also ignores all attempts to programmatically move it to the front). This results in behavior where it *appears* to the user that the program has locked up, because the only windows they can see are non-responsive. If they can get the background window into the foreground, they are good to go... however, that eludes many people. This happened fairly often with older pre-v5 versions of GCS and caused a lot of support burden for me. Due to this, I made sure the new software avoids bringing up secondary windows as much as possible. The edge case still happens, but the occurrence is vastly less with the new setup. Should I ever figure out how to get around this problem, I will likely update the interface to at least allow secondary windows to be more common. Sadly, some OS's document this behavior as a "feature", requiring some sort of interaction with the user to occur to make things work properly -- the issue in those cases is that, for whatever reason, the OS isn't sensing the user as doing that action at some points. I just haven't identified what that would be nor how to remedy it.

2. They have very old machines they are trying to use which do not support a minimum of OpenGL 3.2. This is valid, but not something I'm going to spend any time on, given that is an exceedingly old standard.

**Comment by Viridianus** [comment]
Well, aside from the modal dialogs, back in the day transition actually broke some features; I presume those things were fixed by now but this left a sour taste - probably disregardable.

**Comment by richardwilkes** [comment]
Yes, there were certainly some issues with the first few releases of v5. To be expected with such a sweeping rewrite, unfortunately.

**Comment by Viridianus** [comment]
> What’s the motivation for such a thing? There would have to be significant benefit for me to consider spending any time at all on such a task.

Found a new difference in behavior:
- 4.37 correctly identified Reputation 3 (Almost everyone, x1; Recognized on 7 or less, x1/3) as costing [5]
- The newest version falsely calculates its cost as [4].

Probably an instance of some larger misrepresentation of calculating thirds.

**Comment by richardwilkes** [comment]
That's a data issue where someone entered a multiplier of x0.33 rather than x1/3. Fractions should always be used to retain better accuracy if they can't be exactly represented in decimal. Anyway, open the trait up and adjust the modifier to use the correct multiplier and you should get the correct value.

A general sweep needs to be done through the data files to correct things like this, where data was either entered incorrectly in the first place, or was entered that way due to a limitation in older software. In this case, I'm sure the ability to multiply by a fraction was introduced long after the original data was input, as the Basic Set was the first data file to be created.

**Comment by Viridianus** [comment]
> A general sweep needs to be done through the data files to correct things like this

Well, if you tell me where to find the files, I could do a pull request for ya :)

**Comment by richardwilkes** [comment]
The Master Library repo can be found at https://github.com/richardwilkes/gcs_master_library

Generally, those with the Librarian tag over on the GCS Discord manage edits to it.
