### ISSUE TITLE
Feature Request: Allow intermediate values for self-control rolls 

### ISSUE THREAD

**Issue by gamingballistic** [richardwilkes/gcs#684]
The Dungeon Fantasy RPG lets you modify certain disadvantages to have modifiers to their point values to account for greater and lesser susceptibility to giving into your urges.

For reasons related to the Delvers to Grow work, I was looking at self-control roll numbers, and it turns out the cost multiplier and self-control roll target obey a simple formula. Really simple: Multiplier = 3 – Self-Control Roll/6

More varied self control rolls allow pentaphilia: If you have a disad usually worth -15 points at a Self-Control Roll of 12, it will be worth a friendly -10 points with a target of 14, instead of -7.5 points, rounded against you to a value of -7.

This isn't a big deal or must-have. But for some disads, it's nice to have them available in basically 5-point increments.

**Comment by richardwilkes** [comment]
I was looking at whether to implement your request for more fine-grained CR this evening (i.e. use a formula such as `3 - CR/6` to determine the multiplier). Is this something you actually intend to use, or did you find something else you're going to do after all?
While the formula is easy enough to implement, it is slightly problematic in that it results in a lot of imprecise multipliers. This can be sorted by just doing suitable rounding, which has to be done anyway, but does look odd anywhere the actual multiplier is displayed (i.e. something like x0.6667 will show up).

In addition, there is the matter of the various adjustments that can be derived from them (action penalty, reaction penalty, fright check penalty, fright check bonus, minor cost of living increase, and major cost of living increase) -- it isn't clear how these intermediate values would map into those.

Because of this, I'm currently leaning against implementing this. If you have a solution that makes sense for the adjustments and really need this, I'm open to adding it -- but only if you really need it.

Anyway, please let me know.

**Comment by gamingballistic** [comment]
It's not burning a hole in my to-do list, so if a more pressing use case
comes up, I'll ask again with specifics as to why.

**Comment by richardwilkes** [comment]
Closing this for now. Feel free to re-open if/when you get the specifics you mentioned.
