### ISSUE TITLE
Auto Fit to Window

### ISSUE THREAD

**Issue by Tarrith** [richardwilkes/gcs#692]
Issue: In the Beta version, when PDF's and other items such as pictures that have various sized is opened a user has to resize it manually.
Solution: Have the window automatically fit to window with the option of setting a specific size.

**Comment by richardwilkes** [comment]
When we discussed this yesterday in chat, I thought you were asking for the scaling value of the window to dynamically update as the window was resized to keep the content fully visible. Instead, it sound like your platform (Windows, right?) isn't opening the PDF window to a reasonable size like it does on other platforms. Note that there is a brief pause necessary, since there is no way for me to know the dimensions of the PDF without first loading and rendering portions of it. Due to this, the code currently creates the window, renders the page, then resizes the window to fit the content (but also constrains it to fit on the screen, in the case where the PDF display is taller or wider than your display). If you're not seeing this behavior, then there is something odd going on with Windows and its response to back-to-back window resizing commands... which I know is an issue on Linux, but didn't realize was also one on Windows. Anyway, let me know if that is indeed what you're referring to. Attaching a short video of your screen when this is happening would probably be best for me to understand.

**Comment by Tarrith** [comment]
Ok let me see if I can clarify.
When I open a PDF or a picture it opens up at a default of 100%.
If I maximise the window the picture stays the same size even though the window is now the size of the screen. If it was set to fit window, I wouldn't need to start guessing what adjustment to the % I need to get it to fit proportionally to the window.
It's not a huge issue just a QoL I guess.

I hope that clarifies.

**Comment by richardwilkes** [comment]
OK, so you were asking for what I originally thought you were. Thanks for clarifying.

**Comment by Tarrith** [comment]
Durned english language always messin' up people's undertsnading! ;)
