### ISSUE TITLE
Trojan Alert

### ISSUE THREAD

**Issue by x39aesthetics** [richardwilkes/gcs#715]
The most recent download is flagged by Windows 10 as containing a Trojan
Trojan:Script/Wacatac.B!ml

**Comment by richardwilkes** [comment]
Every release gets flagged by various Windows virus detectors. They don't understand Go code and tend to just flag such binaries because of that. The only way I know of to fix this is to pay Microsoft so that I can digitally sign the binaries, which I'm not willing to do. If you are concerned, you can always build the software yourself from the source.

All that said, if you can show me that it actually contains a virus, I'd be interested. Every single release, however, has been flagged in error, so I'm skeptical. Also, the machine I build the release on is used solely for that purpose -- very little chance of there being a virus present.
