### ISSUE TITLE
Calculation in item notes/note item

### ISSUE THREAD

**Issue by ndrwstn** [richardwilkes/gcs#719]
I'd like to be able to use calculations in item notes (e.g. within a trait such as temperature tolerance to show the calculated temperature value range using HT). Since I suspect the code is reusable, it would also be nice to have a note item with a calculation in it. I suggest wrapping the calcuation in a characters, such as '$<calculation>$' using either single or double characters.

**Comment by richardwilkes** [comment]
The reason I've not added something like this already is that it is far too easy to create circular references which cannot be resolved and can be hard to detect properly to abort resolution (rather than just locking up). Even with a good, fast solution to the detection of such things, the support burden of explaining to people why what they did doesn't work would get old really quick. I already that problem to a lesser degree with the one place where I support expressions (attributes).

I'd love to be able to this, but without a way to ensure I don't get buried in annoyed user support handling, I won't.

**Comment by ndrwstn** [comment]
You could just put it as an optional thing (default off) in preferences and not provide support?

**Comment by richardwilkes** [comment]
With this commit, expressions can now be inserted into the notes field, as well as in the top-level notes object. To use them, you must surround the expression with double vertical bars, like this: `Twice my strength is ||2 * $st||.`
