### ISSUE TITLE
Markdown Files Not Opening*

### ISSUE THREAD

**Issue by TheCalculusKid** [richardwilkes/gcs#720]
I have noticed that markdown files do no open after being pulled from Github and when created using notepad++. When they are edited with notepad++ thinks seems to work fine though. Thanks!

**Comment by richardwilkes** [comment]
As noted in Discord, this is probably due to the NotePad app on Windows suddenly transforming the line endings, which it shouldn't have done. However, this is something that I'd like GCS to be able to cope with, so I should be able to add some code to detect and correct it when other programs mangle the data in this way.
