### ISSUE TITLE
unsatisfied_reason does not appear on skills/techniques that have unsatisfied prerequisites

### ISSUE THREAD

**Issue by dferenc-pannoniacode** [richardwilkes/gcs#721]
```
		{
			"id": "9cd1bbdc-d5f3-437c-907a-4fd8bd78e077",
			"type": "technique",
			"name": "Knee Strike",
			"reference": "B232,MA76",
			"tags": [
				"Combat",
				"Melee Combat",
				"Technique",
				"Weapon"
			],
			"difficulty": "a",
			"points": 1,
			"default": {
				"type": "skill",
				"name": "Brawling",
				"modifier": -1
			},
			"limit": 0
		},
```

This is an example of a skill (technique) that is missing some prerequisites. In this case it's also missing it's whole calc and due to that the reason the unsatisfied_reason property, too.

**Comment by richardwilkes** [comment]
Hmm... this is because techniques have their controlling skill added as a prerequisite without actually stating as much in the data. The code I added for emitting that info previously assumed that you could only have missing prerequisites if you actually had defined prerequisites, which most techniques do not.

Anyway, I'll have to add that at some future point.

**Comment by richardwilkes** [comment]
Turns out it was slightly different than what I was expecting. The issue was due to the resolved level being 0, which short-circuits the normal save logic to save some space. Anyway, I've fixed that oversight.
