### ISSUE TITLE
Improved Third-Party Data Support

### ISSUE THREAD

**Issue by rinickolous** [richardwilkes/gcs#738]
This request essentially just serves as a way to make data parity assurance between GCS and GGA easier, and is as follows:

Allow objects other than just the character itself to have a `third_party` property. It would work almost exactly like the one on the character, but would be placed on items including traits and variants thereof, skills, spells, equipment, weapons, and notes. The important thing is that the `third_party` object content survives the parent item being moved around.

**Comment by richardwilkes** [comment]
Can you give me an example of where this would actually be used?

**Comment by rinickolous** [comment]
Currently, items in GGA have a couple of fields which they don't have in GCS. These would include for example the `img` field which stores image data for the item. There are also the various OTF roll fields which don't exist in GCS.

When GGA 1.0 rolls around, it'll be possible to export GGA characters back to GCS, so I'd like for this to result in as little data loss as possible, and would like to make it convenient for myself as a GGA Dev to handle.

**Comment by richardwilkes** [comment]
There is already a “VTT notes” field for the OTF’s — at least, that’s what it was intended for when I added it, among other things. I believe that exists on most, if not all, of the primary types, with the possible exception of the top-level “notes” type. Not in front of my computer at the moment to check, though.

As for an image… I’d be happy to add that as a first-class field, if it was useful. I find it unlikely that 99% of non-character sheet entities would need a picture, though. Equipment is semi-understandable, but even that is probably highly unlikely, just due to how many images would need to be created.

One of my concerns with adding a third-party blob to every top-level entity is that it could potentially cause significant unwanted bloat, especially since it is effectively invisible to a GCS user.

**Comment by rinickolous** [comment]
I definitely understand the bloat concern. In that case, I'll probably just stick to the existing fields for GGA data.

**Comment by richardwilkes** [comment]
I went ahead and added a `third_party` key to all of the top-level data types. Should I find that this ends up causing problems in some way, I'll remove it in a future release. Hopefully, that won't be necessary.
