### ISSUE TITLE
Can't hide "Rated ST"

### ISSUE THREAD

**Issue by ndrwstn** [richardwilkes/gcs#746]
For 5.11, https://github.com/richardwilkes/gcs/commit/1cd89dc70848a87b8ce5a892d1c2115bfc3f9a58 added 'Rated ST' for equipment. If it's set, it always shows up "inline" even if everything else is turned off. Whether it's displayed should follow either modifiers or notes.

**Comment by richardwilkes** [comment]
This is because the Rated ST is neither a modifier nor a note. That said, a case could be made for treating it as if it were a note. That would necessitate changing its display order to be grouped with the notes, which I'm not sure I like.

**Comment by richardwilkes** [comment]
After trying it out, I'm OK with combining the Rated ST display with the Notes. With the default setting to display both modifiers and notes inline, instead of this:

Equipment Name
Rated ST
Modifiers
Notes

you'll now get this:

Equipment Name
Modifiers
Rated ST; Notes

This change enables the Rated ST to be affected by the choice for Notes display.
