### ISSUE TITLE
Modifier to affect range (for Weapons Quality)

### ISSUE THREAD

**Issue by ndrwstn** [richardwilkes/gcs#747]
Unless I'm missing something, there is no way to create an Equipment Modifier that affects range for muscle-powered ranged weapon quality (B277) that would allow range to be modified.

**Comment by richardwilkes** [comment]
You're not missing anything. There is currently no support for modifiers for most of the fields of a weapon entry. Sometimes, this is because the data is actually just a string that GCS doesn't really know anything about. Other times is just because I've not gotten around to it. In either case, you can always manually override the values, so it hasn't made it very high on my list of things to work on next.

**Comment by richardwilkes** [comment]
Support for this was added in commit df2fbb46e575543fa2ae48c147a5bc398925d7bb
