### ISSUE TITLE
Embedded images in the Notes section cannot find the file on Windows

### ISSUE THREAD

**Issue by saint-thomas-more** [richardwilkes/gcs#761]
![image](https://github.com/richardwilkes/gcs/assets/126619536/19959df3-c81f-4ef9-ad1d-2a0c61835b5a)
![image](https://github.com/richardwilkes/gcs/assets/126619536/a0bbdb07-1a64-4d1f-a97b-f5c4303cd39c)

**Comment by richardwilkes** [comment]
Ah, I should have looked closer last night. The colon after the drive letter should have been replaced with a / too, for it to potentially work. Regardless, I want to make it work with Windows path names -- although that's not portable, while unix-style path names are.

**Comment by saint-thomas-more** [comment]
@richardwilkes 
> The colon after the drive letter should have been replaced with a / too, for it to potentially work. 

This doesn't work. I think I might have brute forced all the combinations of singular and double slashes.

![image](https://github.com/richardwilkes/gcs/assets/126619536/401ae9a0-5ff7-497a-a215-15405bedb158)

But a relative path does! With both types of slashes or double slashes even.

![image](https://github.com/richardwilkes/gcs/assets/126619536/3d7efade-77f2-4e00-8e8c-43ce8b6f9eac)

**Comment by richardwilkes** [comment]
I finally got a spare moment to actually look at the problem here. The real issue is that absolute pathnames aren't supported the way you're expecting. GCS needs to be able to have links in various places that point to the content in the Markdown folder in your library, and where that actually is on disk isn't a fixed location, I decided to make absolute paths root themselves to the "Markdown" folder in each library. So content in the Master Library that provides links can do references like "/foo/bar.md" and those will get translated to <Master Library folder>/Markdown/foo/bar.md, regardless of the location of the file that contains the reference. Relative links still work as you'd expect, relative to the file in question (assuming it has been saved -- a link within a file that hasn't yet been saved to disk at all won't resolve until it is saved the first time).
