### ISSUE TITLE
Add options to display jumping, climbing, and throwing stats

### ISSUE THREAD

**Issue by Angular-Angel** [richardwilkes/gcs#78]
There are some pretty significant equations to determing these stats. Having the sheet automate that the same way it automates most other things would be very helpful.

**Comment by richardwilkes** [comment]
I've not looked to see what is actually necessary to compute these values, but can they not be done now via custom attributes?

**Comment by richardwilkes** [comment]
As of the upcoming v5.4 release, a new function in expressions can be used: `skill_level`, which will allow jumping to be calculated. Looking at the rules for climbing and throwing, there is nothing specific I believe should be on the sheet itself, since they are all very dependent upon the situation.
