### ISSUE TITLE
Clarify spell prerequisite dropdown by changing wording

### ISSUE THREAD

**Issue by ethorad** [richardwilkes/gcs#807]
It seems GCS prerequisites work differently on traits/skills compared to spells.

I can create a trait or a skill called "Test" with prerequisite "Does not have a trait/skill with name Test" and it will flag as an unresolved prerequisite (basically when checking prerequisites it includes itself).  However for spells, if I create a spell called "Test" with prerequisite "Does not have exactly 1 spell with name Test" then it doesn't show as a failed prerequisite.

I assume this is because a lot of spells have prerequisites like "At least 5 other spells from CollegeName", and it can't count the spell in question as one of its own prerequisites.

If so, can the prerequisite box change to show "other spell(s)" rather than "spell(s)" to make this clear?

(I'm doing this in templates where there is sometimes an entry like "spend 2 points improving a different skill".  I add a temporary skill called "Spend 2 points on another skill" with cost 2, and then give it a prerequisite that means it will always flag.  That way users get a visible sign that they need to carry out that action then delete the temporary skill)

**Comment by richardwilkes** [comment]
Trying this just now, I can create a trait, skill and spell and set each to effectively "doesn't have a XXX whose name is YYY" and they all behave the same.

The "doesn't have" always passes, while the "has" never passes for all 3 when only that trait/skill/spell is present. This makes sense, because the item in question isn't considered when looking for prereqs.

Your description above doesn't match what I'm seeing. Perhaps you can attach an example with the absolute minimum showing what you think the problem is?

**Comment by richardwilkes** [comment]
Regarding the request to put the word "other" in front of the type... that's a bit problematic, as the prereq panel is used for all of the standard types and doesn't know what type it is embedded inside of. i.e. the criteria could be on a trait saying "1 spell whose name is Foo", which makes more sense than "1 other spell whose name is Foo" when applied to anything other than a spell.

I'm probably going to just live with the oddity when referring to the same type you're embedded into, as the work to make it contextually aware is probably not worth the effort.

**Comment by richardwilkes** [comment]
Closing this due to a lack of response. Feel free to re-open if/when you have the information requested.
