### ISSUE TITLE
Alternate basic damage

### ISSUE THREAD

**Issue by NagBoard** [richardwilkes/gcs#811]
It would be great to be able to add new damage schemes like we can do with attributes. Main purpose right now is calculating FDG damage automatically, but can be used for other rules. It would probably result in refactoring damage schemes though, because they would be covered under this system and all previous work will become obsolete.

Additional solution might be just creating checkbox in sheet settings to display FDG damage, that would be easier and would not require rewriting the whole damage module. 

![image](https://github.com/richardwilkes/gcs/assets/100212155/bb88fa67-e8fd-4acb-b54c-4188f9c6dac5)

**Comment by SavarWallk** [comment]
I would like something that could be tied to Telekinesis also.

**Comment by richardwilkes** [comment]
Please dig up the relevant rules (with page references, please) on the FDG and TK damages in question and put the info here. I'll then evaluate whether there are any complications with me adding an option to display them in addition to the basic ones (and allowing them to be selected for weapon entries).

Generic formulas aren't generally possible for damage calculations that I've seen so far... and I don't have any interest in opening that up anyway, since it would be very easy to introduce circular references if done incorrectly.

**Comment by SavarWallk** [comment]
Basic Characters: pg92 doesn't outrate say it however every other strength usage you base off your telekinesis level. And that is how it is normally interpreted with everybody that I've gamed under.
Dungeon Fantasy 14 PSI pg11 states that telekinesis strength and move are based off of level of trait.
