### ISSUE TITLE
Keyboard shortcuts seem to assume QWERTY keyboard layout

### ISSUE THREAD

**Issue by dhasenan** [richardwilkes/gcs#819]
I'm using Dvorak. When I hit `Ctrl+N` to open a document, nothing happens. When I hit `Ctrl+B` instead (QWERTY location of 'N'), it creates a new document. Similarly, when I use `Ctrl+Alt+=`, it doesn't zoom in. When I use `Ctrl+Alt+]` instead (QWERTY location of '='), it zooms in.

**Comment by richardwilkes** [comment]
GCS uses what is given to it by the glfw library. Not having any setup that doesn't use QWERTY, I'm not clear on how I'd even test to see what glfw is doing in your case. If you can provide explicit directions on how to setup a Linux box (I'm unwilling to muck with my macOS or Windows boxes for this) with such a configuration so that I can test against it, that would help.

**Comment by richardwilkes** [comment]
I'm closing this since I've not gotten a response from you. Feel free to re-open if you can provide the information required.
