### ISSUE TITLE
Weight for multiple light items incorrectly violates equipment container weight restrictions

### ISSUE THREAD

**Issue by MichaelMalus** [richardwilkes/gcs#82]
In some circumstances, containers with a "Has a contained weight which is at most" restriction give a warning when multiple small items, adding up to the container max, are in them. This isn't the case with single items of the sum weight, or a smaller number of larger objects.

This was discovered/can be reproduced by adding 12 0.1lb Arrows (from the Basic Set library) to the Shoulder Quiver (from the Dungeon Fantasy library).

![image](https://user-images.githubusercontent.com/2191582/45928994-a2369400-bf43-11e8-8b7b-a2973fb56288.png)

**Comment by richardwilkes** [comment]
The problem here is the use of floating-point values for the calculation. “0.1” is not directly representable in binary, giving minute cumulative errors when operations are done with it. 
https://www.exploringbinary.com/why-0-point-1-does-not-exist-in-floating-point/ gives a good explanation, if you’re curious.

Anyway, in a revised version of GCS that I’m working on, I’m no longer using floating point for this sort of thing to fix the problem. Not sure when I will release this, though, as it is part of a much larger re-write.

**Comment by richardwilkes** [comment]
Fixed for the next release.
