### ISSUE TITLE
Custom Self-Control Rolls

### ISSUE THREAD

**Issue by TheFabulousIronChef** [richardwilkes/gcs#822]
It would be really cool if there could be a checkbox for Self-Control Rolls that allow you to have nonstandard multipliers (i.e., other than 6, 9, 12, and 15). It's a very niche case, and I figure a checkbox would be better because allowing it to be "default" would probably result in lots of users annoying their GMs with nonstandard choices. Anyhow, in some cases, a GM might want to allow a different self control number so the points are in multiples of 5. So, for example, Lecherousness [-15] has a self-control roll of 12. It's -22 points at 9, and -7 at 15. It would be a lot better to allow a self control roll of 10 [-20] and 14 [-10]. Here's the progression that I would use. I think it is non-canonical, but I believe Doug from Gaming Ballistic is using it in the solo adventure Saethor's Bane (Lecherousness (14) [-10] is one of the disads in a -25 point disad package). 

Maybe that checkbox would be in settings, so people would really need to look for it (and casual users wouldn't accidentally turn it on so easily). 

![image](https://github.com/richardwilkes/gcs_master_library/assets/46587602/3c4cf0fd-2729-4216-b86d-d6d407266547)

**Comment by richardwilkes** [comment]
commit 59091b2aee2c7ab08966498a00e1b71a1b141ac2

**Comment by richardwilkes** [comment]
Forgot to note: with the supplied multipliers as taken from your table and the fixed-precision math that GCS uses, all of the point values match for your examples except one: for a base -15 point disadvantage with a CR10, the calculations result in a -19, not a -20. I'm not going to try to adjust for this, since I'm sure that there are other similar off-by-one in either direction if you change the base point value to something besides -5, -10, or -15.
