### ISSUE TITLE
Feature request: option to add left, right as options in limbs

### ISSUE THREAD

**Issue by p-thor** [richardwilkes/gcs#83]
When setting DR in an (dis)advantage the option to set specific left or right would be nice.

![screenshot from 2018-10-06 13-50-30](https://user-images.githubusercontent.com/915380/46571076-df9d1780-c96e-11e8-9f46-b16a2039bcba.png)

**Comment by trooper6** [comment]
Agreed. Would especially be useful for GURPS Martial Arts: Gladiators

**Comment by richardwilkes** [comment]
That's not currently practical, solely because of the large amount of additional space on the sheet it would require to support more hit locations. I've often wanted the same myself, though. Coming up with a practical way to display all hit location armor values on the sheet would allow me to add such a feature, as additional hit locations themselves aren't difficult at all.

**Comment by richardwilkes** [comment]
Included as part of #218
