### ISSUE TITLE
skill penalty with crossbow rated ST

### ISSUE THREAD

**Issue by Posbi2** [richardwilkes/gcs#851]
Rated ST does calculate the damage and range now, but there is a skill penalty for using a weapon with higher ST in GCS for all weapons. According to https://forums.sjgames.com/showpost.php?p=383791&postcount=74
the skill penalty uses the weapons type minimum ST, not the specific weapon ST, but B270 forbids the use of a stronger bow.
So I'm not sure about the actual rule for skill penalty using a bow with rated ST in GURPS.

But then DFRPG Adventurers p. 98 only exempts crossbow and prodd from the penalty, not bows.

So I'm at least sure that a crossbow shouldn't get the skill penalty based on rated ST.

**Comment by richardwilkes** [comment]
This text (from your link):

> Originally Posted by Kromm
> Pretty much. Here's the scoop:
> 
> * All BOWS have their own ST value. Bow ST -- and not the user's ST --
> determines range and damage, and must be specified when buying the bow.
> An archer can always use a bow that's weaker than him, but he'll do
> less damage. He cannot use a stronger bow at all. Thus, he'll usually
> want to choose a bow ST that exactly matches his ST.
> 
> * All CROSSBOWS have their own ST value. Crossbow ST -- and not the
> user's ST -- determines range and damage, and must be specified when
> buying the crossbow. A crossbowman can always use a crossbow that's
> weaker than him, but he'll do less damage. He can also use a crossbow
> that's stronger than him to do more damage, but such a crossbow will
> take longer to cock.
> 
> * Neither bow ST nor crossbow ST is in any way related to the "ST" stat
> for those weapons. The "ST" stat is the minimum user ST needed to hold
> a weapon of a particular length and mass on target. For instance, you
> need ST 11 or more to hold a bulky longbow steady and ST 7 or more to
> stabilize a stubby crossbow. If you have less ST, you suffer -1 to hit
> per point of deficiency. You could make a longbow with ST 8 for damage
> and range, and a ST 8 person could draw it -- but he'd be at -3 to hit
> because while he could manage the draw, he couldn't balance a six-foot
> bowstaff steady at arm's reach.
> 
> Anything else is incorrect.

indicates minimum ST is never adjusted for either due to rated ST, which is not what GCS does today. That's definitely not in the rules as written, but Kromm is the line editor, so his statements do hold weight. However, they further complicate an already massively complex area (GURPS weapon stats and their application). Now, I could take this as gospel and assume that any other weapons that might have a rated ST (I can't think of any, but GCS allows for any weapon to have a rated ST) does not in fact affect its minimum ST as well. That would be the easiest thing to do by far. I'm just not sure its the right thing to do.

I'd like to hear more from the community at large before making such a change.

**Comment by TheFabulousIronChef** [comment]
I'm not quite sure what is being sought here--basically, something that would set the ST of the crossbow for damage purposes, but then exempt the ST rating? 

In DFRPG, you can fire a crossbow that is rated 4 higher than your ST; beyond that, you can't cock it. I guess technically _someone else_ could cock it for you and you could walk around with a crossbow that you can't cock, but can fire. 

Currently, that can be done as a work-around as follows:

1. Set the crossbow to the desired rated ST.
2. If the rated ST exceeds the characters ST by x, add a Feature that gives a weapon minimum ST modifier of -x. That cancels out the penalties. Although the better (and arguably, more correct) way would be to reduce the minimum ST of a regular crossbow to 7, and for a composite crossbow to 8, by reducing the minimum ST accordingly. So, for example, a crossbow with rated ST 19 would have -9 to the minimum ST modifier. 

Anyhow, this is a simple workaround to make the minimum ST for the weapon disassociated with the rated ST (because crossbows and prodds are different from bows). 

DFPRG Adventurers p. 98 notes, "_Bows, Crossbows, and ST:_ Bows, crossbows, and prodds have their own **rated ST**, which you must specify when you buy such a weapon. The minimum ST in the table is the lowest possible value. Use the weapon’s rated ST instead of your ST to determine range and damage" and "You can use a stronger crossbow or prodd at no skill penalty, but it will take longer to cock (see Shots, p. 97)."

![image](https://github.com/richardwilkes/gcs/assets/46587602/c20f71c6-e9d2-473e-a9c8-48d88a422df9)
