### ISSUE TITLE
GCS Damage conversion

### ISSUE THREAD

**Issue by Valdagast** [richardwilkes/gcs#857]
GCS make it so that e.g. 12d converts to 6dx2

**Comment by richardwilkes** [comment]
I don't see any rules which state how this is to be performed. Looking through the existing data, I see 2d, 4d, 5d, 6d, 7d, and 8d as the prefix. There may be even more variety, as I got tired of looking after a short while. Anyway, this requires some specific rules/guidelines to point me at before I'll consider it.

**Comment by Valdagast** [comment]
Ok, so a cheap hack then. Just add the ability to write something like 0.5d x2 per level in the damage column and have the computer figure out how much that is. Is that doable?
    Den måndag 29 juli 2024 kl. 01:03:25 CEST, Richard Wilkes ***@***.***> skrev:  
 
 


I don't see any rules which state how this is to be performed. Looking through the existing data, I see 2d, 4d, 5d, 6d, 7d, and 8d as the prefix. There may be even more variety, as I got tired of looking after a short while. Anyway, this requires some specific rules/guidelines to point me at before I'll consider it.

**Comment by richardwilkes** [comment]
That's not really a solution. There are a lot of things I could do here, but all of them are hacks at best. Some dice specifications will have no reasonable conversion, too. For example, what does 13d become? No multiple of whole dice will work, so you have to leave it as-is, or cause it to be larger or smaller than it should be. Other cases, like 12d, could be resolved into many different permutations: 2dx6, 3dx4, 4dx3, 6dx2. Which is the correct one? All 4 styles are present in the data files.

Anyway, I'd like some definitive guidelines from either a GURPS book or from someone like Kromm before I implement something for this. It isn't due to difficulty, but wanting to have it match what the SJG folks do as closely as possible.
