### ISSUE TITLE
Add Support for The Fifth Attribute (Pyramid 120 - Alternate GURPS V /  Thaumtology)

### ISSUE THREAD

**Issue by Ghostwalker7** [richardwilkes/gcs#86]
In the the new Pyramid for the **Alternate GURPS** series, there is an article for a fifth attribute, covering both supernatural resistance, mana, etc. The idea behind the article is not exactly news, and originally appeared in **Thaumatology**, page 29. In short, the articlue create a fifth attribute called _Quintessence (QN)_, that you can use for spells, mana points, and other things.

In the current version of the GCS, I just create the Increased Quintessence (QN) advantage and in the notes session I just write down the appropriate level. But could be nice to have a way to add this news attribute in the sheet somehow, in a way that we could link to spells.

**Comment by richardwilkes** [comment]
Adding arbitrary stats to the software isn't actually all that hard... However, the real issue is always sheet layout with these sorts of changes. To make such things practical, a better layout management system would need to be written to allow someone to better adapt the layout when there are suddenly additional attributes (or whatever else -- there have been requests for all kinds of "extras" found in Pyramid articles that would need sheet overhauls to reasonably work well).

**Comment by richardwilkes** [comment]
Custom attribute support has been implemented and will be in the next release.
