### ISSUE TITLE
Equipment containers

### ISSUE THREAD

**Issue by SavarWallk** [richardwilkes/gcs#900]
Would there be a way to allow equipment modifiers to effect containers instead of the individual pieces inside? 

Example. 
I have an equipment container called comlink. 
I have inside the container a datapad, a tiny computer, and a small FTL radio. 

I want to harden them all. 
However I can't harden the container I have to harden each device individually. 
Which isn't a big deal but I didn't know how easy it would be to modify the containers to accept equipment modifiers.

**Comment by richardwilkes** [comment]
The problem I see with this is that such things aren't generally intrinsic to the container. There is currently one thing that is: a modifier to alter what the container reports as its contained weight (so you can create things like D&D's bag of holding or some of the equipment found in Dungeon Fantasy). This makes sense, since taking an item out of the bag and moving it elsewhere doesn't suddenly remove a property from the equipment that was moved. It makes a lot less sense for something like you mentioned above -- just because you move it from the container, it shouldn't lose its "hardened" state. If these things are separatable, then I'd argue you should just be creating a single item that has all of its abilities and harden that instead.

**Comment by SavarWallk** [comment]
Okay.
I was using the equipment container as the equivalency of a meta-trait container.

If it's a major coding issue I'm not worried about it. Because your points are very valid.
