### ISSUE TITLE
Multi-monitor has it spawn in a nonexistant monitor.

### ISSUE THREAD

**Issue by Velocikitty** [richardwilkes/gcs#906]
I run 4 monitors (I am a streamer), and when I boot up GCS, it always seems to default to an upper left screen that does not exist.

(To explain my setup, 3 on one level, and one on the far upper right above the third)

I'd assume its trying to default to the top left pixel, and not keeping where windows are from before.

**Comment by richardwilkes** [comment]
Odd. Sounds like your system is reporting incorrect display positions if what you say is the case. When GCS starts, if no recorded position has been saved from a previous session, it selects what the system has designated as the "primary" monitor and sets its window to fill that display's usable area. If a previous position is available, then it tries to use the recorded position, but will force the window onto the display with the largest overlap with the position, if it isn't fully within a single monitor.

What platform are you running (Windows/macOS/Linux)?

**Comment by Velocikitty** [comment]
Test

**Comment by Velocikitty** [comment]
Windows 10.

https://i.imgur.com/flsp4sr.png

Here is my layout of monitors:

https://i.imgur.com/Dy0SNcy.png

Oddly enough, this is the only program that does it.

**Comment by richardwilkes** [comment]
After reviewing the code again, I did find a case where it wouldn't adjust the location correctly. I don't know if it will actually help your situation or not, but it is possible. Anyway, on the theory that this change fixed it, I'm closing this for now. If it turns out not to be the case, feel free to re-open it.

Note that you won't see this until the next release or if you build it yourself.

**Comment by Velocikitty** [comment]
Aye, this fixed it.
