### ISSUE TITLE
Scroll up not working on sub windows

### ISSUE THREAD

**Issue by Izradorr** [richardwilkes/gcs#98]
The library window on the left works fine.  The other libraries you bring up in the other windows shows buggy behavior on the scrolling.   Down scroll works fine but up scrolling stops working.  Thats with either mouse wheel or clicking the up arrow.  Moving the scroll bar works fine.  

Windows 10
Chrome

**Comment by richardwilkes** [comment]
You will need to supply specific reproducing behavior, as I don't see any issues on a stock Windows 10 installation. If you have extensions that attempt to alter the Windows user interface in any way, try turning those off, as they are frequently the source of such errors.

**Comment by Izradorr** [comment]
I'm using stock chrome.  The only extension I'm using is Adblock.  I'm not familiar with software development, can you tell me how to "supply specific reproducting behavior?"

**Comment by richardwilkes** [comment]
Chrome has absolutely nothing to do with the app, as it is not run in the browser.

**Comment by richardwilkes** [comment]
By "specific reproducing behavior", I'm asking for explicit steps, from the time you launch the app until you see the error, so that I can try following those exact same steps to reproduce the issue. Right now, everything I try behaves correctly, so I can only assume you are doing something I'm not, or you running in an altered environment -- in which case there isn't much I can do.
